# Electricity Theft Detection

Data Pre - Processing

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('data.csv')
df

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,2016/9/28,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9
0,0387DD8A07E07FDA6271170F86AD9151,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.12,9.96,16.92,7.60,27.22,18.05,26.47,18.75,17.84,14.92
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B32AC8CC6D5D805AC053557AB05F5343,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.50,9.99,11.78,18.59,26.80,18.57,14.59,12.82,19.37,15.92
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.90,3.42,3.81,4.58,3.56,4.25,3.86,3.53,...,17.77,10.37,15.32,13.51,12.23,14.68,16.35,18.14,18.41,17.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42367,F1472871E1AFF49D4289564B6377D76C,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.25,3.56,3.38,4.39,3.72,3.77,3.96,3.64,3.40,4.38
42368,F3C8BBCD2DC26C1E0249DEEF6A4256B7,0,2.70,4.39,3.95,0.00,0.00,0.00,0.00,0.00,...,4.81,4.87,4.48,3.67,3.31,4.58,3.33,3.19,4.57,4.00
42369,A9A0FE83467A680FBFB0DBFC910DF227,0,0.58,0.84,1.61,0.90,0.60,0.82,0.89,0.03,...,NaN,0.66,2.92,2.36,3.86,4.28,3.37,6.67,2.44,1.15
42370,D9A6ADA018FA46A55D5438370456AA45,0,16.89,13.84,13.50,14.60,14.46,12.34,15.37,17.01,...,21.13,13.75,22.61,18.83,25.52,18.11,19.31,17.48,17.20,15.28
42371,F3406636BAD1E6E0826E8EDDC9A1BF00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.80,4.45,9.80,5.11,16.69,12.04,9.90,8.23,8.56,9.86

In [2]:
df.shape

(42372, 1036)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42372 entries, 0 to 42371
Columns: 1036 entries, CONS_NO to 2016/9/9
dtypes: float64(1034), int64(1), object(1)
memory usage: 334.9+ MB

In [4]:
df['FLAG'].value_counts()

FLAG
0    38757
1     3615
Name: count, dtype: int64

In [5]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

CONS_NO           0
FLAG              0
2014/1/1      16502
2014/1/10     16460
2014/1/11     16461
2014/1/12     16460
2014/1/13     16460
2014/1/14     16460
2014/1/15     16457
2014/1/16     16448
2014/1/17     16447
2014/1/18     16447
2014/1/19     16447
2014/1/2      16499
2014/1/20     16444
2014/1/21     16442
2014/1/22     16434
2014/1/23     16437
2014/1/24     16429
2014/1/25     16429
2014/1/26     16431
2014/1/27     16416
2014/1/28     16409
2014/1/29     16402
2014/1/3      16500
2014/1/30     16192
2014/1/31     16192
2014/1/4      16498
2014/1/5      16498
2014/1/6      16494
2014/1/7      16493
2014/1/8      16465
2014/1/9      16465
2014/10/1     12493
2014/10/10    12015
2014/10/11    12164
2014/10/12    12173
2014/10/13    14351
2014/10/14    11908
2014/10/15    12223
2014/10/16    12196
2014/10/17    12220
2014/10/18    12147
2014/10/19    12162
2014/10/2     12414
2014/10/20    12264
2014/10/21    12266
2014/10/22    14142
2014/10/23    13137
2014/10/24    12628
2014/10/25    12538
2014/10/26    12385
2014/10/27    12430
2014/10/28    12164
2014/10/29    12129
2014/10/3     42357
2014/10/30    12041
2014/10/31    12119
2014/10/4     12429
2014/10/5     12312
2014/10/6     14109
2014/10/7     13484
2014/10/8     12001
2014/10/9     12093
2014/11/1     12076
2014/11/10    12085
2014/11/11    12000
2014/11/12    11926
2014/11/13    11846
2014/11/14    11816
2014/11/15    11804
2014/11/16    11795
2014/11/17    11793
2014/11/18    11979
2014/11/19    12379
2014/11/2     12005
2014/11/20    12311
2014/11/21    12057
2014/11/22    12073
2014/11/23    12092
2014/11/24    12096
2014/11/25    12115
2014/11/26    12144
2014/11/27    12327
2014/11/28    12347
2014/11/29    12095
2014/11/3     12049
2014/11/30    12590
2014/11/4     12012
2014/11/5     12262
2014/11/6     12539
2014/11/7     12282
2014/11/8     12146
2014/11/9     12168
2014/12/1     13044
2014/12/10    12189
2014/12/11    12460
2014/12/12    12467
2014/12/13    12191
2014/12/14    12165
2014/12/15    12111
2014/12/16    12151
2014/12/17    12330
2014/12/18    12386
2014/12/19    12421
2014/12/2     12865
2014/12/20    12440
2014/12/21    12585
2014/12/22    12273
2014/12/23    12173
2014/12/24    12208
2014/12/25    13263
2014/12/26    12316
2014/12/27    12386
2014/12/28    12362
2014/12/29    12304
2014/12/3     12697
2014/12/30    12211
2014/12/31    12098
2014/12/4     12415
2014/12/5     12628
2014/12/6     12721
2014/12/7     12557
2014/12/8     12503
2014/12/9     12372
2014/2/1      16192
2014/2/10     16178
2014/2/11     16175
2014/2/12     16176
2014/2/13     16179
2014/2/14     16176
2014/2/15     16175
2014/2/16     16175
2014/2/17     16416
2014/2/18     16411
2014/2/19     16407
2014/2/2      16192
2014/2/20     20536
2014/2/21     19883
2014/2/22     19594
2014/2/23     20494
2014/2/24     20326
2014/2/25     19917
2014/2/26     19880
2014/2/27     20165
2014/2/28     20985
2014/2/3      16192
2014/2/4      16192
2014/2/5      16194
2014/2/6      16195
2014/2/7      16187
2014/2/8      16181
2014/2/9      16181
2014/3/1      20207
2014/3/10     17737
2014/3/11     17775
2014/3/12     17753
2014/3/13     17790
2014/3/14     17849
2014/3/15     17996
2014/3/16     17951
2014/3/17     17994
2014/3/18     17596
2014/3/19     21505
2014/3/2      20224
2014/3/20     18023
2014/3/21     17362
2014/3/22     17606
2014/3/23     19377
2014/3/24     18385
2014/3/25     18315
2014/3/26     19318
2014/3/27     17384
2014/3/28     17725
2014/3/29     17633
2014/3/3      20806
2014/3/30     17503
2014/3/31     17737
2014/3/4      20820
2014/3/5      17963
2014/3/6      17684
2014/3/7      18088
2014/3/8      17975
2014/3/9      17651
2014/4/1      17679
2014/4/10     18978
2014/4/11     19210
2014/4/12     18639
2014/4/13     16985
2014/4/14     16962
2014/4/15     16839
2014/4/16     17065
2014/4/17     17029
2014/4/18     17503
2014/4/19     20633
2014/4/2      17750
2014/4/20     17304
2014/4/21     17284
2014/4/22     17090
2014/4/23     17096
2014/4/24     16631
2014/4/25     17061
2014/4/26     17043
2014/4/27     17091
2014/4/28     17401
2014/4/29     17347
2014/4/3      17551
2014/4/30     17489
2014/4/4      17138
2014/4/5      17065
2014/4/6      17113
2014/4/7      17329
2014/4/8      17400
2014/4/9      19607
2014/5/1      17225
2014/5/10     15999
2014/5/11     15996
2014/5/12     16075
2014/5/13     16231
2014/5/14     16439
2014/5/15     16266
2014/5/16     16055
2014/5/17     15818
2014/5/18     15880
2014/5/19     18908
2014/5/2      17083
2014/5/20     16169
2014/5/21     16339
2014/5/22     16285
2014/5/23     16286
2014/5/24     16135
2014/5/25     16025
2014/5/26     15892
2014/5/27     15890
2014/5/28     15835
2014/5/29     15819
2014/5/3      17105
2014/5/30     15715
2014/5/31     15682
2014/5/4      17126
2014/5/5      16777
2014/5/6      16462
2014/5/7      16438
2014/5/8      16206
2014/5/9      16241
2014/6/1      15775
2014/6/10     15701
2014/6/11     15495
2014/6/12     15193
2014/6/13     14731
2014/6/14     14762
2014/6/15     14842
2014/6/16     14841
2014/6/17     14759
2014/6/18     14743
2014/6/19     16568
2014/6/2      15794
2014/6/20     14620
2014/6/21     14350
2014/6/22     14342
2014/6/23     14606
2014/6/24     14819
2014/6/25     14536
2014/6/26     14508
2014/6/27     14591
2014/6/28     14471
2014/6/29     14241
2014/6/3      15978
2014/6/30     14205
2014/6/4      16261
2014/6/5      15906
2014/6/6      15644
2014/6/7      15139
2014/6/8      15146
2014/6/9      15502
2014/7/1      14177
2014/7/10     14142
2014/7/11     14051
2014/7/12     14251
2014/7/13     14336
2014/7/14     14153
2014/7/15     13970
2014/7/16     14169
2014/7/17     14469
2014/7/18     14725
2014/7/19     14604
2014/7/2      14302
2014/7/20     14573
2014/7/21     14344
2014/7/22     14038
2014/7/23     14250
2014/7/24     14225
2014/7/25     14300
2014/7/26     14166
2014/7/27     14230
2014/7/28     14219
2014/7/29     13745
2014/7/3      14641
2014/7/30     13683
2014/7/31     14274
2014/7/4      14323
2014/7/5      14033
2014/7/6      14345
2014/7/7      14617
2014/7/8      14302
2014/7/9      14638
2014/8/1      14181
2014/8/10     13410
2014/8/11     13446
2014/8/12     13540
2014/8/13     13465
2014/8/14     13320
2014/8/15     13579
2014/8/16     13418
2014/8/17     13244
2014/8/18     13423
2014/8/19     13547
2014/8/2      13761
2014/8/20     13537
2014/8/21     13349
2014/8/22     13490
2014/8/23     13518
2014/8/24     13473
2014/8/25     13426
2014/8/26     13275
2014/8/27     13141
2014/8/28     13178
2014/8/29     13543
2014/8/3      13882
2014/8/30     13467
2014/8/31     13016
2014/8/4      13893
2014/8/5      13739
2014/8/6      13543
2014/8/7      13449
2014/8/8      13650
2014/8/9      13755
2014/9/1      13306
2014/9/10     12455
2014/9/11     12526
2014/9/12     12594
2014/9/13     12504
2014/9/14     12429
2014/9/15     12385
2014/9/16     12402
2014/9/17     12500
2014/9/18     12503
2014/9/19     12398
2014/9/2      13287
2014/9/20     12344
2014/9/21     12371
2014/9/22     12579
2014/9/23     12940
2014/9/24     12932
2014/9/25     12296
2014/9/26     12336
2014/9/27     12383
2014/9/28     12354
2014/9/29     12399
2014/9/3      12643
2014/9/30     12529
2014/9/4      12810
2014/9/5      12726
2014/9/6      12392
2014/9/7      12401
2014/9/8      12371
2014/9/9      12497
2015/1/1      12108
2015/1/10     12357
2015/1/11     12447
2015/1/12     12672
2015/1/13     12603
2015/1/14     12484
2015/1/15     12417
2015/1/16     12333
2015/1/17     12314
2015/1/18     12257
2015/1/19     12417
2015/1/2      12104
2015/1/20     12434
2015/1/21     12319
2015/1/22     12457
2015/1/23     12578
2015/1/24     12480
2015/1/25     12528
2015/1/26     12640
2015/1/27     12510
2015/1/28     12727
2015/1/29     12709
2015/1/3      12190
2015/1/30     12600
2015/1/31     12561
2015/1/4      12246
2015/1/5      12279
2015/1/6      12287
2015/1/7      12303
2015/1/8      12297
2015/1/9      12354
2015/10/1     16781
2015/10/10    17247
2015/10/11    17212
2015/10/12    17212
2015/10/13    17398
2015/10/14    17395
2015/10/15    17505
2015/10/16    17450
2015/10/17    17309
2015/10/18    17303
2015/10/19    17310
2015/10/2     16791
2015/10/20    17354
2015/10/21    17363
2015/10/22    17362
2015/10/23    17383
2015/10/24    17414
2015/10/25    17417
2015/10/26    17343
2015/10/27    17347
2015/10/28    17477
2015/10/29    17479
2015/10/3     16791
2015/10/30    17424
2015/10/31    17419
2015/10/4     16970
2015/10/5     16975
2015/10/6     16785
2015/10/7     16789
2015/10/8     16924
2015/10/9     16958
2015/11/1     17415
2015/11/10    17548
2015/11/11    17511
2015/11/12    17513
2015/11/13    17908
2015/11/14    17929
2015/11/15    17728
2015/11/16    17502
2015/11/17    17498
2015/11/18    17502
2015/11/19    17511
2015/11/2     17521
2015/11/20    17590
2015/11/21    17694
2015/11/22    17772
2015/11/23    17810
2015/11/24    17816
2015/11/25    17917
2015/11/26    17918
2015/11/27    17802
2015/11/28    17798
2015/11/29    17818
2015/11/3     17558
2015/11/30    17847
2015/11/4     17762
2015/11/5     17708
2015/11/6     17481
2015/11/7     17490
2015/11/8     17494
2015/11/9     17541
2015/12/1     17819
2015/12/10    18028
2015/12/11    18033
2015/12/12    18028
2015/12/13    18074
2015/12/14    18205
2015/12/15    18186
2015/12/16    18272
2015/12/17    18329
2015/12/18    18605
2015/12/19    18627
2015/12/2     17824
2015/12/20    18454
2015/12/21    18386
2015/12/22    18321
2015/12/23    18436
2015/12/24    18454
2015/12/25    18421
2015/12/26    18468
2015/12/27    18487
2015/12/28    18437
2015/12/29    18398
2015/12/3     17850
2015/12/30    18391
2015/12/31    18399
2015/12/4     17857
2015/12/5     18050
2015/12/6     18085
2015/12/7     18004
2015/12/8     18022
2015/12/9     18020
2015/2/1      12597
2015/2/10     12696
2015/2/11     12788
2015/2/12     12993
2015/2/13     13240
2015/2/14     13087
2015/2/15     13095
2015/2/16     13337
2015/2/17     13536
2015/2/18     13388
2015/2/19     13394
2015/2/2      12559
2015/2/20     13289
2015/2/21     13231
2015/2/22     13315
2015/2/23     13300
2015/2/24     13303
2015/2/25     13309
2015/2/26     13073
2015/2/27     13100
2015/2/28     13221
2015/2/3      12653
2015/2/4      12690
2015/2/5      12644
2015/2/6      12549
2015/2/7      12539
2015/2/8      12548
2015/2/9      12667
2015/3/1      13224
2015/3/10     13135
2015/3/11     13157
2015/3/12     13185
2015/3/13     13225
2015/3/14     13210
2015/3/15     13232
2015/3/16     13246
2015/3/17     13381
2015/3/18     13767
2015/3/19     13723
2015/3/2      13137
2015/3/20     13437
2015/3/21     13471
2015/3/22     13448
2015/3/23     13294
2015/3/24     13304
2015/3/25     13450
2015/3/26     13530
2015/3/27     13465
2015/3/28     13335
2015/3/29     13317
2015/3/3      13115
2015/3/30     13268
2015/3/31     13572
2015/3/4      13122
2015/3/5      13119
2015/3/6      13086
2015/3/7      13219
2015/3/8      13276
2015/3/9      13286
2015/4/1      13608
2015/4/10     13413
2015/4/11     13295
2015/4/12     13287
2015/4/13     13280
2015/4/14     13289
2015/4/15     13292
2015/4/16     13339
2015/4/17     13370
2015/4/18     13337
2015/4/19     13337
2015/4/2      13727
2015/4/20     13358
2015/4/21     13369
2015/4/22     13354
2015/4/23     13712
2015/4/24     13750
2015/4/25     13785
2015/4/26     13779
2015/4/27     13855
2015/4/28     13853
2015/4/29     13816
2015/4/3      13974
2015/4/30     13840
2015/4/4      13707
2015/4/5      13426
2015/4/6      13508
2015/4/7      13393
2015/4/8      13373
2015/4/9      13463
2015/5/1      13777
2015/5/10     14139
2015/5/11     14079
2015/5/12     14099
2015/5/13     14102
2015/5/14     14105
2015/5/15     14159
2015/5/16     14148
2015/5/17     14113
2015/5/18     14115
2015/5/19     14123
2015/5/2      13791
2015/5/20     14145
2015/5/21     14110
2015/5/22     14332
2015/5/23     14507
2015/5/24     14513
2015/5/25     14455
2015/5/26     14446
2015/5/27     14495
2015/5/28     14496
2015/5/29     14441
2015/5/3      13798
2015/5/30     14584
2015/5/31     14572
2015/5/4      13859
2015/5/5      14046
2015/5/6      14150
2015/5/7      14189
2015/5/8      14283
2015/5/9      14138
2015/6/1      14458
2015/6/10     14603
2015/6/11     14566
2015/6/12     14801
2015/6/13     14753
2015/6/14     14500
2015/6/15     14560
2015/6/16     14759
2015/6/17     14796
2015/6/18     14895
2015/6/19     14891
2015/6/2      14469
2015/6/20     14869
2015/6/21     14977
2015/6/22     14970
2015/6/23     14782
2015/6/24     14803
2015/6/25     14822
2015/6/26     14896
2015/6/27     15088
2015/6/28     15052
2015/6/29     14858
2015/6/3      14632
2015/6/30     14832
2015/6/4      14626
2015/6/5      14604
2015/6/6      14690
2015/6/7      14730
2015/6/8      14756
2015/6/9      14830
2015/7/1      14869
2015/7/10     15188
2015/7/11     15184
2015/7/12     15183
2015/7/13     15244
2015/7/14     15503
2015/7/15     15469
2015/7/16     15253
2015/7/17     15272
2015/7/18     15174
2015/7/19     15297
2015/7/2      14908
2015/7/20     15309
2015/7/21     15276
2015/7/22     15356
2015/7/23     15278
2015/7/24     15521
2015/7/25     15621
2015/7/26     15580
2015/7/27     15845
2015/7/28     15878
2015/7/29     15764
2015/7/3      15108
2015/7/30     15699
2015/7/31     15952
2015/7/4      15078
2015/7/5      15032
2015/7/6      15041
2015/7/7      15148
2015/7/8      15181
2015/7/9      15145
2015/8/1      15943
2015/8/10     17222
2015/8/11     16631
2015/8/12     16448
2015/8/13     16447
2015/8/14     16231
2015/8/15     16121
2015/8/16     16158
2015/8/17     16189
2015/8/18     16200
2015/8/19     16180
2015/8/2      15936
2015/8/20     16227
2015/8/21     16238
2015/8/22     16309
2015/8/23     16464
2015/8/24     16505
2015/8/25     16660
2015/8/26     16679
2015/8/27     16523
2015/8/28     16453
2015/8/29     16439
2015/8/3      15816
2015/8/30     16467
2015/8/31     16485
2015/8/4      15809
2015/8/5      15847
2015/8/6      15849
2015/8/7      16414
2015/8/8      19450
2015/8/9      19166
2015/9/1      16478
2015/9/10     16540
2015/9/11     16553
2015/9/12     16502
2015/9/13     16549
2015/9/14     16586
2015/9/15     16610
2015/9/16     16691
2015/9/17     16718
2015/9/18     16859
2015/9/19     16825
2015/9/2      16479
2015/9/20     16775
2015/9/21     16691
2015/9/22     16895
2015/9/23     16899
2015/9/24     16880
2015/9/25     16774
2015/9/26     16754
2015/9/27     16785
2015/9/28     16934
2015/9/29     16822
2015/9/3      16479
2015/9/30     16785
2015/9/4      16520
2015/9/5      16516
2015/9/6      16516
2015/9/7      16516
2015/9/8      16508
2015/9/9      16514
2016/1/1        512
2016/1/10       634
2016/1/11       907
2016/1/12       929
2016/1/13       555
2016/1/14       634
2016/1/15       573
2016/1/16       504
2016/1/17       491
2016/1/18       592
2016/1/19       626
2016/1/2        506
2016/1/20       667
2016/1/21       645
2016/1/22       629
2016/1/23       607
2016/1/24       605
2016/1/25       646
2016/1/26       769
2016/1/27       831
2016/1/28       866
2016/1/29       838
2016/1/3        518
2016/1/30       780
2016/1/31       745
2016/1/4        530
2016/1/5        532
2016/1/6        865
2016/1/7        895
2016/1/8        607
2016/1/9        498
2016/10/1      1081
2016/10/10      732
2016/10/11      758
2016/10/12      541
2016/10/13      544
2016/10/14      756
2016/10/15      785
2016/10/16     1041
2016/10/17      802
2016/10/18      692
2016/10/19      568
2016/10/2       768
2016/10/20      517
2016/10/21      539
2016/10/22      526
2016/10/23      548
2016/10/24      552
2016/10/25      707
2016/10/26      749
2016/10/27      975
2016/10/28      929
2016/10/29      735
2016/10/3       711
2016/10/30      738
2016/10/31      803
2016/10/4       779
2016/10/5       674
2016/10/6       659
2016/10/7       663
2016/10/8       681
2016/10/9       674
2016/2/1        863
2016/2/10       773
2016/2/11      1004
2016/2/12      1202
2016/2/13       916
2016/2/14      1072
2016/2/15      1039
2016/2/16       843
2016/2/17       744
2016/2/18       697
2016/2/19       663
2016/2/2        947
2016/2/20       673
2016/2/21       925
2016/2/22       912
2016/2/23       580
2016/2/24       567
2016/2/25       544
2016/2/26       810
2016/2/27       829
2016/2/28       608
2016/2/29       724
2016/2/3        828
2016/2/4        688
2016/2/5        700
2016/2/6        727
2016/2/7       1082
2016/2/8       1070
2016/2/9        781
2016/3/1        728
2016/3/10       539
2016/3/11       546
2016/3/12       539
2016/3/13       654
2016/3/14       705
2016/3/15       767
2016/3/16       667
2016/3/17       468
2016/3/18       476
2016/3/19       478
2016/3/2        757
2016/3/20       473
2016/3/21       434
2016/3/22       593
2016/3/23       595
2016/3/24       533
2016/3/25       545
2016/3/26       437
2016/3/27       510
2016/3/28       581
2016/3/29       766
2016/3/3        690
2016/3/30       687
2016/3/31       589
2016/3/4        692
2016/3/5        664
2016/3/6        614
2016/3/7        929
2016/3/8        952
2016/3/9        544
2016/4/1        476
2016/4/10       613
2016/4/11       592
2016/4/12       610
2016/4/13       601
2016/4/14       591
2016/4/15       547
2016/4/16       539
2016/4/17       562
2016/4/18       556
2016/4/19       537
2016/4/2        494
2016/4/20       557
2016/4/21       560
2016/4/22       516
2016/4/23       475
2016/4/24       463
2016/4/25       442
2016/4/26       447
2016/4/27       493
2016/4/28       458
2016/4/29       443
2016/4/3        496
2016/4/30       507
2016/4/4        482
2016/4/5        480
2016/4/6        493
2016/4/7        696
2016/4/8        684
2016/4/9        632
2016/5/1        504
2016/5/10       644
2016/5/11       774
2016/5/12       779
2016/5/13       793
2016/5/14       699
2016/5/15       460
2016/5/16       475
2016/5/17       619
2016/5/18       699
2016/5/19       655
2016/5/2        526
2016/5/20       592
2016/5/21       712
2016/5/22       784
2016/5/23       620
2016/5/24       526
2016/5/25       472
2016/5/26       701
2016/5/27       921
2016/5/28       663
2016/5/29       682
2016/5/3        656
2016/5/30       774
2016/5/31       619
2016/5/4        659
2016/5/5        646
2016/5/6        583
2016/5/7        870
2016/5/8        842
2016/5/9        670
2016/6/1        521
2016/6/10       693
2016/6/11       698
2016/6/12       653
2016/6/13       636
2016/6/14       701
2016/6/15       639
2016/6/16       611
2016/6/17       623
2016/6/18       663
2016/6/19       633
2016/6/2        606
2016/6/20       640
2016/6/21       631
2016/6/22       568
2016/6/23       510
2016/6/24       533
2016/6/25       533
2016/6/26       602
2016/6/27       750
2016/6/28       796
2016/6/29       737
2016/6/3        655
2016/6/30       643
2016/6/4        559
2016/6/5        527
2016/6/6        483
2016/6/7        438
2016/6/8        453
2016/6/9        400
2016/7/1        606
2016/7/10       583
2016/7/11       755
2016/7/12       697
2016/7/13       849
2016/7/14       619
2016/7/15       469
2016/7/16       448
2016/7/17       490
2016/7/18       487
2016/7/19       461
2016/7/2        578
2016/7/20       493
2016/7/21       490
2016/7/22       443
2016/7/23       442
2016/7/24       492
2016/7/25       515
2016/7/26       603
2016/7/27       765
2016/7/28       838
2016/7/29       554
2016/7/3        606
2016/7/30       505
2016/7/31       540
2016/7/4        734
2016/7/5        693
2016/7/6        581
2016/7/7        552
2016/7/8        516
2016/7/9        568
2016/8/1        556
2016/8/10       530
2016/8/11       429
2016/8/12       434
2016/8/13       445
2016/8/14       525
2016/8/15       531
2016/8/16       702
2016/8/17       692
2016/8/18       578
2016/8/19       617
2016/8/2        512
2016/8/20       518
2016/8/21       558
2016/8/22       689
2016/8/23       741
2016/8/24       728
2016/8/25      1002
2016/8/26       858
2016/8/27       876
2016/8/28       892
2016/8/29       796
2016/8/3        521
2016/8/30       883

In [6]:
# Get all date columns automatically
date_columns = [col for col in df.columns if col not in ['CONS_NO', 'FLAG']]

# Then use it:
df['mean_consumption'] = df[date_columns].mean(axis=1)

In [7]:
df.head()

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,mean_consumption
0,0387DD8A07E07FDA6271170F86AD9151,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.96,16.92,7.60,27.22,18.05,26.47,18.75,17.84,14.92,13.898342
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.000000
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.921390
3,B32AC8CC6D5D805AC053557AB05F5343,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.99,11.78,18.59,26.80,18.57,14.59,12.82,19.37,15.92,14.612055
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.9,3.42,3.81,4.58,3.56,4.25,3.86,3.53,...,10.37,15.32,13.51,12.23,14.68,16.35,18.14,18.41,17.31,8.249738

In [8]:
date_columns = [col for col in df.columns if col not in ['CONS_NO', 'FLAG']]

# Fill each row's NaN with that row's mean
df[date_columns] = df[date_columns].apply(
    lambda row: row.fillna(row.mean()), 
    axis=1
)

In [9]:
df.head()

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,mean_consumption
0,0387DD8A07E07FDA6271170F86AD9151,1,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,9.96000,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000,13.898342
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.000000
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.921390
3,B32AC8CC6D5D805AC053557AB05F5343,1,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,9.99000,11.78000,18.59000,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000,14.612055
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,...,10.37000,15.32000,13.51000,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000,8.249738

In [10]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

CONS_NO             0
FLAG                0
2014/1/1            5
2014/1/10           5
2014/1/11           5
2014/1/12           5
2014/1/13           5
2014/1/14           5
2014/1/15           5
2014/1/16           5
2014/1/17           5
2014/1/18           5
2014/1/19           5
2014/1/2            5
2014/1/20           5
2014/1/21           5
2014/1/22           5
2014/1/23           5
2014/1/24           5
2014/1/25           5
2014/1/26           5
2014/1/27           5
2014/1/28           5
2014/1/29           5
2014/1/3            5
2014/1/30           5
2014/1/31           5
2014/1/4            5
2014/1/5            5
2014/1/6            5
2014/1/7            5
2014/1/8            5
2014/1/9            5
2014/10/1           5
2014/10/10          5
2014/10/11          5
2014/10/12          5
2014/10/13          5
2014/10/14          5
2014/10/15          5
2014/10/16          5
2014/10/17          5
2014/10/18          5
2014/10/19          5
2014/10/2           5
2014/10/20          5
2014/10/21          5
2014/10/22          5
2014/10/23          5
2014/10/24          5
2014/10/25          5
2014/10/26          5
2014/10/27          5
2014/10/28          5
2014/10/29          5
2014/10/3           5
2014/10/30          5
2014/10/31          5
2014/10/4           5
2014/10/5           5
2014/10/6           5
2014/10/7           5
2014/10/8           5
2014/10/9           5
2014/11/1           5
2014/11/10          5
2014/11/11          5
2014/11/12          5
2014/11/13          5
2014/11/14          5
2014/11/15          5
2014/11/16          5
2014/11/17          5
2014/11/18          5
2014/11/19          5
2014/11/2           5
2014/11/20          5
2014/11/21          5
2014/11/22          5
2014/11/23          5
2014/11/24          5
2014/11/25          5
2014/11/26          5
2014/11/27          5
2014/11/28          5
2014/11/29          5
2014/11/3           5
2014/11/30          5
2014/11/4           5
2014/11/5           5
2014/11/6           5
2014/11/7           5
2014/11/8           5
2014/11/9           5
2014/12/1           5
2014/12/10          5
2014/12/11          5
2014/12/12          5
2014/12/13          5
2014/12/14          5
2014/12/15          5
2014/12/16          5
2014/12/17          5
2014/12/18          5
2014/12/19          5
2014/12/2           5
2014/12/20          5
2014/12/21          5
2014/12/22          5
2014/12/23          5
2014/12/24          5
2014/12/25          5
2014/12/26          5
2014/12/27          5
2014/12/28          5
2014/12/29          5
2014/12/3           5
2014/12/30          5
2014/12/31          5
2014/12/4           5
2014/12/5           5
2014/12/6           5
2014/12/7           5
2014/12/8           5
2014/12/9           5
2014/2/1            5
2014/2/10           5
2014/2/11           5
2014/2/12           5
2014/2/13           5
2014/2/14           5
2014/2/15           5
2014/2/16           5
2014/2/17           5
2014/2/18           5
2014/2/19           5
2014/2/2            5
2014/2/20           5
2014/2/21           5
2014/2/22           5
2014/2/23           5
2014/2/24           5
2014/2/25           5
2014/2/26           5
2014/2/27           5
2014/2/28           5
2014/2/3            5
2014/2/4            5
2014/2/5            5
2014/2/6            5
2014/2/7            5
2014/2/8            5
2014/2/9            5
2014/3/1            5
2014/3/10           5
2014/3/11           5
2014/3/12           5
2014/3/13           5
2014/3/14           5
2014/3/15           5
2014/3/16           5
2014/3/17           5
2014/3/18           5
2014/3/19           5
2014/3/2            5
2014/3/20           5
2014/3/21           5
2014/3/22           5
2014/3/23           5
2014/3/24           5
2014/3/25           5
2014/3/26           5
2014/3/27           5
2014/3/28           5
2014/3/29           5
2014/3/3            5
2014/3/30           5
2014/3/31           5
2014/3/4            5
2014/3/5            5
2014/3/6            5
2014/3/7            5
2014/3/8            5
2014/3/9            5
2014/4/1            5
2014/4/10           5
2014/4/11           5
2014/4/12           5
2014/4/13           5
2014/4/14           5
2014/4/15           5
2014/4/16           5
2014/4/17           5
2014/4/18           5
2014/4/19           5
2014/4/2            5
2014/4/20           5
2014/4/21           5
2014/4/22           5
2014/4/23           5
2014/4/24           5
2014/4/25           5
2014/4/26           5
2014/4/27           5
2014/4/28           5
2014/4/29           5
2014/4/3            5
2014/4/30           5
2014/4/4            5
2014/4/5            5
2014/4/6            5
2014/4/7            5
2014/4/8            5
2014/4/9            5
2014/5/1            5
2014/5/10           5
2014/5/11           5
2014/5/12           5
2014/5/13           5
2014/5/14           5
2014/5/15           5
2014/5/16           5
2014/5/17           5
2014/5/18           5
2014/5/19           5
2014/5/2            5
2014/5/20           5
2014/5/21           5
2014/5/22           5
2014/5/23           5
2014/5/24           5
2014/5/25           5
2014/5/26           5
2014/5/27           5
2014/5/28           5
2014/5/29           5
2014/5/3            5
2014/5/30           5
2014/5/31           5
2014/5/4            5
2014/5/5            5
2014/5/6            5
2014/5/7            5
2014/5/8            5
2014/5/9            5
2014/6/1            5
2014/6/10           5
2014/6/11           5
2014/6/12           5
2014/6/13           5
2014/6/14           5
2014/6/15           5
2014/6/16           5
2014/6/17           5
2014/6/18           5
2014/6/19           5
2014/6/2            5
2014/6/20           5
2014/6/21           5
2014/6/22           5
2014/6/23           5
2014/6/24           5
2014/6/25           5
2014/6/26           5
2014/6/27           5
2014/6/28           5
2014/6/29           5
2014/6/3            5
2014/6/30           5
2014/6/4            5
2014/6/5            5
2014/6/6            5
2014/6/7            5
2014/6/8            5
2014/6/9            5
2014/7/1            5
2014/7/10           5
2014/7/11           5
2014/7/12           5
2014/7/13           5
2014/7/14           5
2014/7/15           5
2014/7/16           5
2014/7/17           5
2014/7/18           5
2014/7/19           5
2014/7/2            5
2014/7/20           5
2014/7/21           5
2014/7/22           5
2014/7/23           5
2014/7/24           5
2014/7/25           5
2014/7/26           5
2014/7/27           5
2014/7/28           5
2014/7/29           5
2014/7/3            5
2014/7/30           5
2014/7/31           5
2014/7/4            5
2014/7/5            5
2014/7/6            5
2014/7/7            5
2014/7/8            5
2014/7/9            5
2014/8/1            5
2014/8/10           5
2014/8/11           5
2014/8/12           5
2014/8/13           5
2014/8/14           5
2014/8/15           5
2014/8/16           5
2014/8/17           5
2014/8/18           5
2014/8/19           5
2014/8/2            5
2014/8/20           5
2014/8/21           5
2014/8/22           5
2014/8/23           5
2014/8/24           5
2014/8/25           5
2014/8/26           5
2014/8/27           5
2014/8/28           5
2014/8/29           5
2014/8/3            5
2014/8/30           5
2014/8/31           5
2014/8/4            5
2014/8/5            5
2014/8/6            5
2014/8/7            5
2014/8/8            5
2014/8/9            5
2014/9/1            5
2014/9/10           5
2014/9/11           5
2014/9/12           5
2014/9/13           5
2014/9/14           5
2014/9/15           5
2014/9/16           5
2014/9/17           5
2014/9/18           5
2014/9/19           5
2014/9/2            5
2014/9/20           5
2014/9/21           5
2014/9/22           5
2014/9/23           5
2014/9/24           5
2014/9/25           5
2014/9/26           5
2014/9/27           5
2014/9/28           5
2014/9/29           5
2014/9/3            5
2014/9/30           5
2014/9/4            5
2014/9/5            5
2014/9/6            5
2014/9/7            5
2014/9/8            5
2014/9/9            5
2015/1/1            5
2015/1/10           5
2015/1/11           5
2015/1/12           5
2015/1/13           5
2015/1/14           5
2015/1/15           5
2015/1/16           5
2015/1/17           5
2015/1/18           5
2015/1/19           5
2015/1/2            5
2015/1/20           5
2015/1/21           5
2015/1/22           5
2015/1/23           5
2015/1/24           5
2015/1/25           5
2015/1/26           5
2015/1/27           5
2015/1/28           5
2015/1/29           5
2015/1/3            5
2015/1/30           5
2015/1/31           5
2015/1/4            5
2015/1/5            5
2015/1/6            5
2015/1/7            5
2015/1/8            5
2015/1/9            5
2015/10/1           5
2015/10/10          5
2015/10/11          5
2015/10/12          5
2015/10/13          5
2015/10/14          5
2015/10/15          5
2015/10/16          5
2015/10/17          5
2015/10/18          5
2015/10/19          5
2015/10/2           5
2015/10/20          5
2015/10/21          5
2015/10/22          5
2015/10/23          5
2015/10/24          5
2015/10/25          5
2015/10/26          5
2015/10/27          5
2015/10/28          5
2015/10/29          5
2015/10/3           5
2015/10/30          5
2015/10/31          5
2015/10/4           5
2015/10/5           5
2015/10/6           5
2015/10/7           5
2015/10/8           5
2015/10/9           5
2015/11/1           5
2015/11/10          5
2015/11/11          5
2015/11/12          5
2015/11/13          5
2015/11/14          5
2015/11/15          5
2015/11/16          5
2015/11/17          5
2015/11/18          5
2015/11/19          5
2015/11/2           5
2015/11/20          5
2015/11/21          5
2015/11/22          5
2015/11/23          5
2015/11/24          5
2015/11/25          5
2015/11/26          5
2015/11/27          5
2015/11/28          5
2015/11/29          5
2015/11/3           5
2015/11/30          5
2015/11/4           5
2015/11/5           5
2015/11/6           5
2015/11/7           5
2015/11/8           5
2015/11/9           5
2015/12/1           5
2015/12/10          5
2015/12/11          5
2015/12/12          5
2015/12/13          5
2015/12/14          5
2015/12/15          5
2015/12/16          5
2015/12/17          5
2015/12/18          5
2015/12/19          5
2015/12/2           5
2015/12/20          5
2015/12/21          5
2015/12/22          5
2015/12/23          5
2015/12/24          5
2015/12/25          5
2015/12/26          5
2015/12/27          5
2015/12/28          5
2015/12/29          5
2015/12/3           5
2015/12/30          5
2015/12/31          5
2015/12/4           5
2015/12/5           5
2015/12/6           5
2015/12/7           5
2015/12/8           5
2015/12/9           5
2015/2/1            5
2015/2/10           5
2015/2/11           5
2015/2/12           5
2015/2/13           5
2015/2/14           5
2015/2/15           5
2015/2/16           5
2015/2/17           5
2015/2/18           5
2015/2/19           5
2015/2/2            5
2015/2/20           5
2015/2/21           5
2015/2/22           5
2015/2/23           5
2015/2/24           5
2015/2/25           5
2015/2/26           5
2015/2/27           5
2015/2/28           5
2015/2/3            5
2015/2/4            5
2015/2/5            5
2015/2/6            5
2015/2/7            5
2015/2/8            5
2015/2/9            5
2015/3/1            5
2015/3/10           5
2015/3/11           5
2015/3/12           5
2015/3/13           5
2015/3/14           5
2015/3/15           5
2015/3/16           5
2015/3/17           5
2015/3/18           5
2015/3/19           5
2015/3/2            5
2015/3/20           5
2015/3/21           5
2015/3/22           5
2015/3/23           5
2015/3/24           5
2015/3/25           5
2015/3/26           5
2015/3/27           5
2015/3/28           5
2015/3/29           5
2015/3/3            5
2015/3/30           5
2015/3/31           5
2015/3/4            5
2015/3/5            5
2015/3/6            5
2015/3/7            5
2015/3/8            5
2015/3/9            5
2015/4/1            5
2015/4/10           5
2015/4/11           5
2015/4/12           5
2015/4/13           5
2015/4/14           5
2015/4/15           5
2015/4/16           5
2015/4/17           5
2015/4/18           5
2015/4/19           5
2015/4/2            5
2015/4/20           5
2015/4/21           5
2015/4/22           5
2015/4/23           5
2015/4/24           5
2015/4/25           5
2015/4/26           5
2015/4/27           5
2015/4/28           5
2015/4/29           5
2015/4/3            5
2015/4/30           5
2015/4/4            5
2015/4/5            5
2015/4/6            5
2015/4/7            5
2015/4/8            5
2015/4/9            5
2015/5/1            5
2015/5/10           5
2015/5/11           5
2015/5/12           5
2015/5/13           5
2015/5/14           5
2015/5/15           5
2015/5/16           5
2015/5/17           5
2015/5/18           5
2015/5/19           5
2015/5/2            5
2015/5/20           5
2015/5/21           5
2015/5/22           5
2015/5/23           5
2015/5/24           5
2015/5/25           5
2015/5/26           5
2015/5/27           5
2015/5/28           5
2015/5/29           5
2015/5/3            5
2015/5/30           5
2015/5/31           5
2015/5/4            5
2015/5/5            5
2015/5/6            5
2015/5/7            5
2015/5/8            5
2015/5/9            5
2015/6/1            5
2015/6/10           5
2015/6/11           5
2015/6/12           5
2015/6/13           5
2015/6/14           5
2015/6/15           5
2015/6/16           5
2015/6/17           5
2015/6/18           5
2015/6/19           5
2015/6/2            5
2015/6/20           5
2015/6/21           5
2015/6/22           5
2015/6/23           5
2015/6/24           5
2015/6/25           5
2015/6/26           5
2015/6/27           5
2015/6/28           5
2015/6/29           5
2015/6/3            5
2015/6/30           5
2015/6/4            5
2015/6/5            5
2015/6/6            5
2015/6/7            5
2015/6/8            5
2015/6/9            5
2015/7/1            5
2015/7/10           5
2015/7/11           5
2015/7/12           5
2015/7/13           5
2015/7/14           5
2015/7/15           5
2015/7/16           5
2015/7/17           5
2015/7/18           5
2015/7/19           5
2015/7/2            5
2015/7/20           5
2015/7/21           5
2015/7/22           5
2015/7/23           5
2015/7/24           5
2015/7/25           5
2015/7/26           5
2015/7/27           5
2015/7/28           5
2015/7/29           5
2015/7/3            5
2015/7/30           5
2015/7/31           5
2015/7/4            5
2015/7/5            5
2015/7/6            5
2015/7/7            5
2015/7/8            5
2015/7/9            5
2015/8/1            5
2015/8/10           5
2015/8/11           5
2015/8/12           5
2015/8/13           5
2015/8/14           5
2015/8/15           5
2015/8/16           5
2015/8/17           5
2015/8/18           5
2015/8/19           5
2015/8/2            5
2015/8/20           5
2015/8/21           5
2015/8/22           5
2015/8/23           5
2015/8/24           5
2015/8/25           5
2015/8/26           5
2015/8/27           5
2015/8/28           5
2015/8/29           5
2015/8/3            5
2015/8/30           5
2015/8/31           5
2015/8/4            5
2015/8/5            5
2015/8/6            5
2015/8/7            5
2015/8/8            5
2015/8/9            5
2015/9/1            5
2015/9/10           5
2015/9/11           5
2015/9/12           5
2015/9/13           5
2015/9/14           5
2015/9/15           5
2015/9/16           5
2015/9/17           5
2015/9/18           5
2015/9/19           5
2015/9/2            5
2015/9/20           5
2015/9/21           5
2015/9/22           5
2015/9/23           5
2015/9/24           5
2015/9/25           5
2015/9/26           5
2015/9/27           5
2015/9/28           5
2015/9/29           5
2015/9/3            5
2015/9/30           5
2015/9/4            5
2015/9/5            5
2015/9/6            5
2015/9/7            5
2015/9/8            5
2015/9/9            5
2016/1/1            5
2016/1/10           5
2016/1/11           5
2016/1/12           5
2016/1/13           5
2016/1/14           5
2016/1/15           5
2016/1/16           5
2016/1/17           5
2016/1/18           5
2016/1/19           5
2016/1/2            5
2016/1/20           5
2016/1/21           5
2016/1/22           5
2016/1/23           5
2016/1/24           5
2016/1/25           5
2016/1/26           5
2016/1/27           5
2016/1/28           5
2016/1/29           5
2016/1/3            5
2016/1/30           5
2016/1/31           5
2016/1/4            5
2016/1/5            5
2016/1/6            5
2016/1/7            5
2016/1/8            5
2016/1/9            5
2016/10/1           5
2016/10/10          5
2016/10/11          5
2016/10/12          5
2016/10/13          5
2016/10/14          5
2016/10/15          5
2016/10/16          5
2016/10/17          5
2016/10/18          5
2016/10/19          5
2016/10/2           5
2016/10/20          5
2016/10/21          5
2016/10/22          5
2016/10/23          5
2016/10/24          5
2016/10/25          5
2016/10/26          5
2016/10/27          5
2016/10/28          5
2016/10/29          5
2016/10/3           5
2016/10/30          5
2016/10/31          5
2016/10/4           5
2016/10/5           5
2016/10/6           5
2016/10/7           5
2016/10/8           5
2016/10/9           5
2016/2/1            5
2016/2/10           5
2016/2/11           5
2016/2/12           5
2016/2/13           5
2016/2/14           5
2016/2/15           5
2016/2/16           5
2016/2/17           5
2016/2/18           5
2016/2/19           5
2016/2/2            5
2016/2/20           5
2016/2/21           5
2016/2/22           5
2016/2/23           5
2016/2/24           5
2016/2/25           5
2016/2/26           5
2016/2/27           5
2016/2/28           5
2016/2/29           5
2016/2/3            5
2016/2/4            5
2016/2/5            5
2016/2/6            5
2016/2/7            5
2016/2/8            5
2016/2/9            5
2016/3/1            5
2016/3/10           5
2016/3/11           5
2016/3/12           5
2016/3/13           5
2016/3/14           5
2016/3/15           5
2016/3/16           5
2016/3/17           5
2016/3/18           5
2016/3/19           5
2016/3/2            5
2016/3/20           5
2016/3/21           5
2016/3/22           5
2016/3/23           5
2016/3/24           5
2016/3/25           5
2016/3/26           5
2016/3/27           5
2016/3/28           5
2016/3/29           5
2016/3/3            5
2016/3/30           5
2016/3/31           5
2016/3/4            5
2016/3/5            5
2016/3/6            5
2016/3/7            5
2016/3/8            5
2016/3/9            5
2016/4/1            5
2016/4/10           5
2016/4/11           5
2016/4/12           5
2016/4/13           5
2016/4/14           5
2016/4/15           5
2016/4/16           5
2016/4/17           5
2016/4/18           5
2016/4/19           5
2016/4/2            5
2016/4/20           5
2016/4/21           5
2016/4/22           5
2016/4/23           5
2016/4/24           5
2016/4/25           5
2016/4/26           5
2016/4/27           5
2016/4/28           5
2016/4/29           5
2016/4/3            5
2016/4/30           5
2016/4/4            5
2016/4/5            5
2016/4/6            5
2016/4/7            5
2016/4/8            5
2016/4/9            5
2016/5/1            5
2016/5/10           5
2016/5/11           5
2016/5/12           5
2016/5/13           5
2016/5/14           5
2016/5/15           5
2016/5/16           5
2016/5/17           5
2016/5/18           5
2016/5/19           5
2016/5/2            5
2016/5/20           5
2016/5/21           5
2016/5/22           5
2016/5/23           5
2016/5/24           5
2016/5/25           5
2016/5/26           5
2016/5/27           5
2016/5/28           5
2016/5/29           5
2016/5/3            5
2016/5/30           5
2016/5/31           5

In [11]:
num_null_rows = df[date_columns].isnull().all(axis=1).sum()
print("Number of rows completely null in date columns:", num_null_rows)

Number of rows completely null in date columns: 5

In [12]:
null_cons_numbers = df.loc[df[date_columns].isnull().all(axis=1), 'CONS_NO']
print("Consumers with all null values in date columns:")
print(null_cons_numbers)

Consumers with all null values in date columns:
419      58C5C2F9D81EA5DC8421CACB0C73E495
686      6BE983A5063B5DF9225ADD95AD3F241B
3028     2B981D4283253BA362DB2915358B88BF
37830    D176EB392233366F6F38E46AA592154E
41998    A63E94C418356023D70BE00B7FE2C4EE
Name: CONS_NO, dtype: object

In [13]:
df = df[~df[date_columns].isnull().all(axis=1)]

In [14]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

CONS_NO             0
FLAG                0
2014/1/1            0
2014/1/10           0
2014/1/11           0
2014/1/12           0
2014/1/13           0
2014/1/14           0
2014/1/15           0
2014/1/16           0
2014/1/17           0
2014/1/18           0
2014/1/19           0
2014/1/2            0
2014/1/20           0
2014/1/21           0
2014/1/22           0
2014/1/23           0
2014/1/24           0
2014/1/25           0
2014/1/26           0
2014/1/27           0
2014/1/28           0
2014/1/29           0
2014/1/3            0
2014/1/30           0
2014/1/31           0
2014/1/4            0
2014/1/5            0
2014/1/6            0
2014/1/7            0
2014/1/8            0
2014/1/9            0
2014/10/1           0
2014/10/10          0
2014/10/11          0
2014/10/12          0
2014/10/13          0
2014/10/14          0
2014/10/15          0
2014/10/16          0
2014/10/17          0
2014/10/18          0
2014/10/19          0
2014/10/2           0
2014/10/20          0
2014/10/21          0
2014/10/22          0
2014/10/23          0
2014/10/24          0
2014/10/25          0
2014/10/26          0
2014/10/27          0
2014/10/28          0
2014/10/29          0
2014/10/3           0
2014/10/30          0
2014/10/31          0
2014/10/4           0
2014/10/5           0
2014/10/6           0
2014/10/7           0
2014/10/8           0
2014/10/9           0
2014/11/1           0
2014/11/10          0
2014/11/11          0
2014/11/12          0
2014/11/13          0
2014/11/14          0
2014/11/15          0
2014/11/16          0
2014/11/17          0
2014/11/18          0
2014/11/19          0
2014/11/2           0
2014/11/20          0
2014/11/21          0
2014/11/22          0
2014/11/23          0
2014/11/24          0
2014/11/25          0
2014/11/26          0
2014/11/27          0
2014/11/28          0
2014/11/29          0
2014/11/3           0
2014/11/30          0
2014/11/4           0
2014/11/5           0
2014/11/6           0
2014/11/7           0
2014/11/8           0
2014/11/9           0
2014/12/1           0
2014/12/10          0
2014/12/11          0
2014/12/12          0
2014/12/13          0
2014/12/14          0
2014/12/15          0
2014/12/16          0
2014/12/17          0
2014/12/18          0
2014/12/19          0
2014/12/2           0
2014/12/20          0
2014/12/21          0
2014/12/22          0
2014/12/23          0
2014/12/24          0
2014/12/25          0
2014/12/26          0
2014/12/27          0
2014/12/28          0
2014/12/29          0
2014/12/3           0
2014/12/30          0
2014/12/31          0
2014/12/4           0
2014/12/5           0
2014/12/6           0
2014/12/7           0
2014/12/8           0
2014/12/9           0
2014/2/1            0
2014/2/10           0
2014/2/11           0
2014/2/12           0
2014/2/13           0
2014/2/14           0
2014/2/15           0
2014/2/16           0
2014/2/17           0
2014/2/18           0
2014/2/19           0
2014/2/2            0
2014/2/20           0
2014/2/21           0
2014/2/22           0
2014/2/23           0
2014/2/24           0
2014/2/25           0
2014/2/26           0
2014/2/27           0
2014/2/28           0
2014/2/3            0
2014/2/4            0
2014/2/5            0
2014/2/6            0
2014/2/7            0
2014/2/8            0
2014/2/9            0
2014/3/1            0
2014/3/10           0
2014/3/11           0
2014/3/12           0
2014/3/13           0
2014/3/14           0
2014/3/15           0
2014/3/16           0
2014/3/17           0
2014/3/18           0
2014/3/19           0
2014/3/2            0
2014/3/20           0
2014/3/21           0
2014/3/22           0
2014/3/23           0
2014/3/24           0
2014/3/25           0
2014/3/26           0
2014/3/27           0
2014/3/28           0
2014/3/29           0
2014/3/3            0
2014/3/30           0
2014/3/31           0
2014/3/4            0
2014/3/5            0
2014/3/6            0
2014/3/7            0
2014/3/8            0
2014/3/9            0
2014/4/1            0
2014/4/10           0
2014/4/11           0
2014/4/12           0
2014/4/13           0
2014/4/14           0
2014/4/15           0
2014/4/16           0
2014/4/17           0
2014/4/18           0
2014/4/19           0
2014/4/2            0
2014/4/20           0
2014/4/21           0
2014/4/22           0
2014/4/23           0
2014/4/24           0
2014/4/25           0
2014/4/26           0
2014/4/27           0
2014/4/28           0
2014/4/29           0
2014/4/3            0
2014/4/30           0
2014/4/4            0
2014/4/5            0
2014/4/6            0
2014/4/7            0
2014/4/8            0
2014/4/9            0
2014/5/1            0
2014/5/10           0
2014/5/11           0
2014/5/12           0
2014/5/13           0
2014/5/14           0
2014/5/15           0
2014/5/16           0
2014/5/17           0
2014/5/18           0
2014/5/19           0
2014/5/2            0
2014/5/20           0
2014/5/21           0
2014/5/22           0
2014/5/23           0
2014/5/24           0
2014/5/25           0
2014/5/26           0
2014/5/27           0
2014/5/28           0
2014/5/29           0
2014/5/3            0
2014/5/30           0
2014/5/31           0
2014/5/4            0
2014/5/5            0
2014/5/6            0
2014/5/7            0
2014/5/8            0
2014/5/9            0
2014/6/1            0
2014/6/10           0
2014/6/11           0
2014/6/12           0
2014/6/13           0
2014/6/14           0
2014/6/15           0
2014/6/16           0
2014/6/17           0
2014/6/18           0
2014/6/19           0
2014/6/2            0
2014/6/20           0
2014/6/21           0
2014/6/22           0
2014/6/23           0
2014/6/24           0
2014/6/25           0
2014/6/26           0
2014/6/27           0
2014/6/28           0
2014/6/29           0
2014/6/3            0
2014/6/30           0
2014/6/4            0
2014/6/5            0
2014/6/6            0
2014/6/7            0
2014/6/8            0
2014/6/9            0
2014/7/1            0
2014/7/10           0
2014/7/11           0
2014/7/12           0
2014/7/13           0
2014/7/14           0
2014/7/15           0
2014/7/16           0
2014/7/17           0
2014/7/18           0
2014/7/19           0
2014/7/2            0
2014/7/20           0
2014/7/21           0
2014/7/22           0
2014/7/23           0
2014/7/24           0
2014/7/25           0
2014/7/26           0
2014/7/27           0
2014/7/28           0
2014/7/29           0
2014/7/3            0
2014/7/30           0
2014/7/31           0
2014/7/4            0
2014/7/5            0
2014/7/6            0
2014/7/7            0
2014/7/8            0
2014/7/9            0
2014/8/1            0
2014/8/10           0
2014/8/11           0
2014/8/12           0
2014/8/13           0
2014/8/14           0
2014/8/15           0
2014/8/16           0
2014/8/17           0
2014/8/18           0
2014/8/19           0
2014/8/2            0
2014/8/20           0
2014/8/21           0
2014/8/22           0
2014/8/23           0
2014/8/24           0
2014/8/25           0
2014/8/26           0
2014/8/27           0
2014/8/28           0
2014/8/29           0
2014/8/3            0
2014/8/30           0
2014/8/31           0
2014/8/4            0
2014/8/5            0
2014/8/6            0
2014/8/7            0
2014/8/8            0
2014/8/9            0
2014/9/1            0
2014/9/10           0
2014/9/11           0
2014/9/12           0
2014/9/13           0
2014/9/14           0
2014/9/15           0
2014/9/16           0
2014/9/17           0
2014/9/18           0
2014/9/19           0
2014/9/2            0
2014/9/20           0
2014/9/21           0
2014/9/22           0
2014/9/23           0
2014/9/24           0
2014/9/25           0
2014/9/26           0
2014/9/27           0
2014/9/28           0
2014/9/29           0
2014/9/3            0
2014/9/30           0
2014/9/4            0
2014/9/5            0
2014/9/6            0
2014/9/7            0
2014/9/8            0
2014/9/9            0
2015/1/1            0
2015/1/10           0
2015/1/11           0
2015/1/12           0
2015/1/13           0
2015/1/14           0
2015/1/15           0
2015/1/16           0
2015/1/17           0
2015/1/18           0
2015/1/19           0
2015/1/2            0
2015/1/20           0
2015/1/21           0
2015/1/22           0
2015/1/23           0
2015/1/24           0
2015/1/25           0
2015/1/26           0
2015/1/27           0
2015/1/28           0
2015/1/29           0
2015/1/3            0
2015/1/30           0
2015/1/31           0
2015/1/4            0
2015/1/5            0
2015/1/6            0
2015/1/7            0
2015/1/8            0
2015/1/9            0
2015/10/1           0
2015/10/10          0
2015/10/11          0
2015/10/12          0
2015/10/13          0
2015/10/14          0
2015/10/15          0
2015/10/16          0
2015/10/17          0
2015/10/18          0
2015/10/19          0
2015/10/2           0
2015/10/20          0
2015/10/21          0
2015/10/22          0
2015/10/23          0
2015/10/24          0
2015/10/25          0
2015/10/26          0
2015/10/27          0
2015/10/28          0
2015/10/29          0
2015/10/3           0
2015/10/30          0
2015/10/31          0
2015/10/4           0
2015/10/5           0
2015/10/6           0
2015/10/7           0
2015/10/8           0
2015/10/9           0
2015/11/1           0
2015/11/10          0
2015/11/11          0
2015/11/12          0
2015/11/13          0
2015/11/14          0
2015/11/15          0
2015/11/16          0
2015/11/17          0
2015/11/18          0
2015/11/19          0
2015/11/2           0
2015/11/20          0
2015/11/21          0
2015/11/22          0
2015/11/23          0
2015/11/24          0
2015/11/25          0
2015/11/26          0
2015/11/27          0
2015/11/28          0
2015/11/29          0
2015/11/3           0
2015/11/30          0
2015/11/4           0
2015/11/5           0
2015/11/6           0
2015/11/7           0
2015/11/8           0
2015/11/9           0
2015/12/1           0
2015/12/10          0
2015/12/11          0
2015/12/12          0
2015/12/13          0
2015/12/14          0
2015/12/15          0
2015/12/16          0
2015/12/17          0
2015/12/18          0
2015/12/19          0
2015/12/2           0
2015/12/20          0
2015/12/21          0
2015/12/22          0
2015/12/23          0
2015/12/24          0
2015/12/25          0
2015/12/26          0
2015/12/27          0
2015/12/28          0
2015/12/29          0
2015/12/3           0
2015/12/30          0
2015/12/31          0
2015/12/4           0
2015/12/5           0
2015/12/6           0
2015/12/7           0
2015/12/8           0
2015/12/9           0
2015/2/1            0
2015/2/10           0
2015/2/11           0
2015/2/12           0
2015/2/13           0
2015/2/14           0
2015/2/15           0
2015/2/16           0
2015/2/17           0
2015/2/18           0
2015/2/19           0
2015/2/2            0
2015/2/20           0
2015/2/21           0
2015/2/22           0
2015/2/23           0
2015/2/24           0
2015/2/25           0
2015/2/26           0
2015/2/27           0
2015/2/28           0
2015/2/3            0
2015/2/4            0
2015/2/5            0
2015/2/6            0
2015/2/7            0
2015/2/8            0
2015/2/9            0
2015/3/1            0
2015/3/10           0
2015/3/11           0
2015/3/12           0
2015/3/13           0
2015/3/14           0
2015/3/15           0
2015/3/16           0
2015/3/17           0
2015/3/18           0
2015/3/19           0
2015/3/2            0
2015/3/20           0
2015/3/21           0
2015/3/22           0
2015/3/23           0
2015/3/24           0
2015/3/25           0
2015/3/26           0
2015/3/27           0
2015/3/28           0
2015/3/29           0
2015/3/3            0
2015/3/30           0
2015/3/31           0
2015/3/4            0
2015/3/5            0
2015/3/6            0
2015/3/7            0
2015/3/8            0
2015/3/9            0
2015/4/1            0
2015/4/10           0
2015/4/11           0
2015/4/12           0
2015/4/13           0
2015/4/14           0
2015/4/15           0
2015/4/16           0
2015/4/17           0
2015/4/18           0
2015/4/19           0
2015/4/2            0
2015/4/20           0
2015/4/21           0
2015/4/22           0
2015/4/23           0
2015/4/24           0
2015/4/25           0
2015/4/26           0
2015/4/27           0
2015/4/28           0
2015/4/29           0
2015/4/3            0
2015/4/30           0
2015/4/4            0
2015/4/5            0
2015/4/6            0
2015/4/7            0
2015/4/8            0
2015/4/9            0
2015/5/1            0
2015/5/10           0
2015/5/11           0
2015/5/12           0
2015/5/13           0
2015/5/14           0
2015/5/15           0
2015/5/16           0
2015/5/17           0
2015/5/18           0
2015/5/19           0
2015/5/2            0
2015/5/20           0
2015/5/21           0
2015/5/22           0
2015/5/23           0
2015/5/24           0
2015/5/25           0
2015/5/26           0
2015/5/27           0
2015/5/28           0
2015/5/29           0
2015/5/3            0
2015/5/30           0
2015/5/31           0
2015/5/4            0
2015/5/5            0
2015/5/6            0
2015/5/7            0
2015/5/8            0
2015/5/9            0
2015/6/1            0
2015/6/10           0
2015/6/11           0
2015/6/12           0
2015/6/13           0
2015/6/14           0
2015/6/15           0
2015/6/16           0
2015/6/17           0
2015/6/18           0
2015/6/19           0
2015/6/2            0
2015/6/20           0
2015/6/21           0
2015/6/22           0
2015/6/23           0
2015/6/24           0
2015/6/25           0
2015/6/26           0
2015/6/27           0
2015/6/28           0
2015/6/29           0
2015/6/3            0
2015/6/30           0
2015/6/4            0
2015/6/5            0
2015/6/6            0
2015/6/7            0
2015/6/8            0
2015/6/9            0
2015/7/1            0
2015/7/10           0
2015/7/11           0
2015/7/12           0
2015/7/13           0
2015/7/14           0
2015/7/15           0
2015/7/16           0
2015/7/17           0
2015/7/18           0
2015/7/19           0
2015/7/2            0
2015/7/20           0
2015/7/21           0
2015/7/22           0
2015/7/23           0
2015/7/24           0
2015/7/25           0
2015/7/26           0
2015/7/27           0
2015/7/28           0
2015/7/29           0
2015/7/3            0
2015/7/30           0
2015/7/31           0
2015/7/4            0
2015/7/5            0
2015/7/6            0
2015/7/7            0
2015/7/8            0
2015/7/9            0
2015/8/1            0
2015/8/10           0
2015/8/11           0
2015/8/12           0
2015/8/13           0
2015/8/14           0
2015/8/15           0
2015/8/16           0
2015/8/17           0
2015/8/18           0
2015/8/19           0
2015/8/2            0
2015/8/20           0
2015/8/21           0
2015/8/22           0
2015/8/23           0
2015/8/24           0
2015/8/25           0
2015/8/26           0
2015/8/27           0
2015/8/28           0
2015/8/29           0
2015/8/3            0
2015/8/30           0
2015/8/31           0
2015/8/4            0
2015/8/5            0
2015/8/6            0
2015/8/7            0
2015/8/8            0
2015/8/9            0
2015/9/1            0
2015/9/10           0
2015/9/11           0
2015/9/12           0
2015/9/13           0
2015/9/14           0
2015/9/15           0
2015/9/16           0
2015/9/17           0
2015/9/18           0
2015/9/19           0
2015/9/2            0
2015/9/20           0
2015/9/21           0
2015/9/22           0
2015/9/23           0
2015/9/24           0
2015/9/25           0
2015/9/26           0
2015/9/27           0
2015/9/28           0
2015/9/29           0
2015/9/3            0
2015/9/30           0
2015/9/4            0
2015/9/5            0
2015/9/6            0
2015/9/7            0
2015/9/8            0
2015/9/9            0
2016/1/1            0
2016/1/10           0
2016/1/11           0
2016/1/12           0
2016/1/13           0
2016/1/14           0
2016/1/15           0
2016/1/16           0
2016/1/17           0
2016/1/18           0
2016/1/19           0
2016/1/2            0
2016/1/20           0
2016/1/21           0
2016/1/22           0
2016/1/23           0
2016/1/24           0
2016/1/25           0
2016/1/26           0
2016/1/27           0
2016/1/28           0
2016/1/29           0
2016/1/3            0
2016/1/30           0
2016/1/31           0
2016/1/4            0
2016/1/5            0
2016/1/6            0
2016/1/7            0
2016/1/8            0
2016/1/9            0
2016/10/1           0
2016/10/10          0
2016/10/11          0
2016/10/12          0
2016/10/13          0
2016/10/14          0
2016/10/15          0
2016/10/16          0
2016/10/17          0
2016/10/18          0
2016/10/19          0
2016/10/2           0
2016/10/20          0
2016/10/21          0
2016/10/22          0
2016/10/23          0
2016/10/24          0
2016/10/25          0
2016/10/26          0
2016/10/27          0
2016/10/28          0
2016/10/29          0
2016/10/3           0
2016/10/30          0
2016/10/31          0
2016/10/4           0
2016/10/5           0
2016/10/6           0
2016/10/7           0
2016/10/8           0
2016/10/9           0
2016/2/1            0
2016/2/10           0
2016/2/11           0
2016/2/12           0
2016/2/13           0
2016/2/14           0
2016/2/15           0
2016/2/16           0
2016/2/17           0
2016/2/18           0
2016/2/19           0
2016/2/2            0
2016/2/20           0
2016/2/21           0
2016/2/22           0
2016/2/23           0
2016/2/24           0
2016/2/25           0
2016/2/26           0
2016/2/27           0
2016/2/28           0
2016/2/29           0
2016/2/3            0
2016/2/4            0
2016/2/5            0
2016/2/6            0
2016/2/7            0
2016/2/8            0
2016/2/9            0
2016/3/1            0
2016/3/10           0
2016/3/11           0
2016/3/12           0
2016/3/13           0
2016/3/14           0
2016/3/15           0
2016/3/16           0
2016/3/17           0
2016/3/18           0
2016/3/19           0
2016/3/2            0
2016/3/20           0
2016/3/21           0
2016/3/22           0
2016/3/23           0
2016/3/24           0
2016/3/25           0
2016/3/26           0
2016/3/27           0
2016/3/28           0
2016/3/29           0
2016/3/3            0
2016/3/30           0
2016/3/31           0
2016/3/4            0
2016/3/5            0
2016/3/6            0
2016/3/7            0
2016/3/8            0
2016/3/9            0
2016/4/1            0
2016/4/10           0
2016/4/11           0
2016/4/12           0
2016/4/13           0
2016/4/14           0
2016/4/15           0
2016/4/16           0
2016/4/17           0
2016/4/18           0
2016/4/19           0
2016/4/2            0
2016/4/20           0
2016/4/21           0
2016/4/22           0
2016/4/23           0
2016/4/24           0
2016/4/25           0
2016/4/26           0
2016/4/27           0
2016/4/28           0
2016/4/29           0
2016/4/3            0
2016/4/30           0
2016/4/4            0
2016/4/5            0
2016/4/6            0
2016/4/7            0
2016/4/8            0
2016/4/9            0
2016/5/1            0
2016/5/10           0
2016/5/11           0
2016/5/12           0
2016/5/13           0
2016/5/14           0
2016/5/15           0
2016/5/16           0
2016/5/17           0
2016/5/18           0
2016/5/19           0
2016/5/2            0
2016/5/20           0
2016/5/21           0
2016/5/22           0
2016/5/23           0
2016/5/24           0
2016/5/25           0
2016/5/26           0
2016/5/27           0
2016/5/28           0
2016/5/29           0
2016/5/3            0
2016/5/30           0
2016/5/31           0

In [15]:
df.shape

(42367, 1037)

In [16]:
df.head()

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,mean_consumption
0,0387DD8A07E07FDA6271170F86AD9151,1,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,9.96000,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000,13.898342
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.000000
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.921390
3,B32AC8CC6D5D805AC053557AB05F5343,1,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,9.99000,11.78000,18.59000,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000,14.612055
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,...,10.37000,15.32000,13.51000,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000,8.249738

In [17]:
df = df.copy()  # To avoid SettingWithCopyWarning
df.drop('mean_consumption', axis=1, inplace=True)

In [18]:
df.head()

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,2016/9/28,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9
0,0387DD8A07E07FDA6271170F86AD9151,1,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,10.12000,9.96000,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139
3,B32AC8CC6D5D805AC053557AB05F5343,1,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,6.50000,9.99000,11.78000,18.59000,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,...,17.77000,10.37000,15.32000,13.51000,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000

In [19]:
df = df.copy()  # To avoid SettingWithCopyWarning
df.drop('CONS_NO', axis=1, inplace=True)

In [20]:
df.head()

,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,...,2016/9/28,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9
0,1,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,10.12000,9.96000,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000
1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
2,1,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139
3,1,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,6.50000,9.99000,11.78000,18.59000,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000
4,1,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,...,17.77000,10.37000,15.32000,13.51000,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000

In [21]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import grad
from sklearn.preprocessing import MinMaxScaler

In [22]:
# Separate features and FLAG
X = df.drop("FLAG", axis=1)
y = df["FLAG"]

# Minority class (theft = 1)
X_minority = X[y == 1]

# Normalize features
scaler = MinMaxScaler()
X_minority_scaled = scaler.fit_transform(X_minority)

X_minority_tensor = torch.tensor(X_minority_scaled, dtype=torch.float32)

In [23]:
class Generator(nn.Module):
    def __init__(self, noise_dim, output_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(noise_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim)
        )

    def forward(self, z):
        return self.model(z)

In [24]:
class Critic(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 128),
            nn.LeakyReLU(0.2),
            nn.Linear(128, 1)
        )

    def forward(self, x):
        return self.model(x)

In [25]:
def gradient_penalty(critic, real, fake):
    batch_size = real.size(0)
    epsilon = torch.rand(batch_size, 1).to(real.device)
    epsilon = epsilon.expand_as(real)

    interpolated = epsilon * real + (1 - epsilon) * fake
    interpolated.requires_grad_(True)

    mixed_scores = critic(interpolated)

    grad_outputs = torch.ones_like(mixed_scores)
    gradients = grad(
        outputs=mixed_scores,
        inputs=interpolated,
        grad_outputs=grad_outputs,
        create_graph=True,
        retain_graph=True,
        only_inputs=True
    )[0]

    gradients = gradients.view(gradients.size(0), -1)
    gp = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
    return gp

In [26]:
device = "cuda" if torch.cuda.is_available() else "cpu"

latent_dim = 32
lr = 1e-4
epochs = 800
batch_size = 128
lambda_gp = 10
n_critic = 5

G = Generator(latent_dim, X_minority.shape[1]).to(device)
D = Critic(X_minority.shape[1]).to(device)

opt_G = optim.Adam(G.parameters(), lr=lr, betas=(0.5, 0.9))
opt_D = optim.Adam(D.parameters(), lr=lr, betas=(0.5, 0.9))

data_loader = torch.utils.data.DataLoader(
    X_minority_tensor, batch_size=batch_size, shuffle=True
)

for epoch in range(epochs):
    for real in data_loader:
        real = real.to(device)

        # Train Critic
        for _ in range(n_critic):
            z = torch.randn(real.size(0), latent_dim).to(device)
            fake = G(z)

            real_score = D(real)
            fake_score = D(fake.detach())

            gp = gradient_penalty(D, real, fake)
            d_loss = fake_score.mean() - real_score.mean() + lambda_gp * gp

            opt_D.zero_grad()
            d_loss.backward()
            opt_D.step()

        # Train Generator
        z = torch.randn(real.size(0), latent_dim).to(device)
        fake = G(z)
        g_loss = -D(fake).mean()

        opt_G.zero_grad()
        g_loss.backward()
        opt_G.step()

    if epoch % 200 == 0:
        print(f"Epoch [{epoch}/{epochs}] | D Loss: {d_loss.item():.4f} | G Loss: {g_loss.item():.4f}")

Epoch [0/800] | D Loss: -1.0908 | G Loss: 1.0976
Epoch [200/800] | D Loss: 0.0017 | G Loss: -3.1665
Epoch [400/800] | D Loss: -0.2033 | G Loss: -1.4039
Epoch [600/800] | D Loss: 0.0006 | G Loss: -2.4732

In [27]:
num_synthetic = 8000   # choose based on imbalance

z = torch.randn(num_synthetic, latent_dim).to(device)
synthetic_data = G(z).detach().cpu().numpy()

synthetic_data = scaler.inverse_transform(synthetic_data)

In [28]:
X_aug = np.vstack([X, synthetic_data])
y_aug = np.hstack([y, np.ones(num_synthetic)])

In [29]:
# Convert to DataFrame
synthetic_df = pd.DataFrame(
    synthetic_data,
    columns=X.columns
)

# Add target label (minority class = 1)
synthetic_df["FLAG"] = 1

In [30]:
original_df = df.copy()
augmented_df = pd.concat([original_df, synthetic_df], ignore_index=True)

In [31]:
augmented_df = augmented_df.sample(frac=1).reset_index(drop=True)

In [32]:
augmented_df['FLAG'].value_counts()

FLAG
0    38755
1    11612
Name: count, dtype: int64

In [33]:
count_0 = sum(y == 0)
count_1 = sum(y == 1)

In [34]:
num_synthetic = count_0 - count_1

In [35]:
z = torch.randn(num_synthetic, latent_dim).to(device)
synthetic_data = G(z).detach().cpu().numpy()

In [36]:
X_aug = np.vstack([X, synthetic_data])
y_aug = np.hstack([y, np.ones(num_synthetic)])

In [37]:
import pandas as pd

df_final = pd.DataFrame(X_aug, columns=X.columns)
df_final["FLAG"] = y_aug

In [38]:
print(df_final.shape)
print(df_final['FLAG'].value_counts())

(77510, 1035)
FLAG
1.0    38755
0.0    38755
Name: count, dtype: int64

In [39]:
pd.set_option('display.max_rows', None)
df_final.isnull().sum()

2014/1/1      0
2014/1/10     0
2014/1/11     0
2014/1/12     0
2014/1/13     0
2014/1/14     0
2014/1/15     0
2014/1/16     0
2014/1/17     0
2014/1/18     0
2014/1/19     0
2014/1/2      0
2014/1/20     0
2014/1/21     0
2014/1/22     0
2014/1/23     0
2014/1/24     0
2014/1/25     0
2014/1/26     0
2014/1/27     0
2014/1/28     0
2014/1/29     0
2014/1/3      0
2014/1/30     0
2014/1/31     0
2014/1/4      0
2014/1/5      0
2014/1/6      0
2014/1/7      0
2014/1/8      0
2014/1/9      0
2014/10/1     0
2014/10/10    0
2014/10/11    0
2014/10/12    0
2014/10/13    0
2014/10/14    0
2014/10/15    0
2014/10/16    0
2014/10/17    0
2014/10/18    0
2014/10/19    0
2014/10/2     0
2014/10/20    0
2014/10/21    0
2014/10/22    0
2014/10/23    0
2014/10/24    0
2014/10/25    0
2014/10/26    0
2014/10/27    0
2014/10/28    0
2014/10/29    0
2014/10/3     0
2014/10/30    0
2014/10/31    0
2014/10/4     0
2014/10/5     0
2014/10/6     0
2014/10/7     0
2014/10/8     0
2014/10/9     0
2014/11/1     0
2014/11/10    0
2014/11/11    0
2014/11/12    0
2014/11/13    0
2014/11/14    0
2014/11/15    0
2014/11/16    0
2014/11/17    0
2014/11/18    0
2014/11/19    0
2014/11/2     0
2014/11/20    0
2014/11/21    0
2014/11/22    0
2014/11/23    0
2014/11/24    0
2014/11/25    0
2014/11/26    0
2014/11/27    0
2014/11/28    0
2014/11/29    0
2014/11/3     0
2014/11/30    0
2014/11/4     0
2014/11/5     0
2014/11/6     0
2014/11/7     0
2014/11/8     0
2014/11/9     0
2014/12/1     0
2014/12/10    0
2014/12/11    0
2014/12/12    0
2014/12/13    0
2014/12/14    0
2014/12/15    0
2014/12/16    0
2014/12/17    0
2014/12/18    0
2014/12/19    0
2014/12/2     0
2014/12/20    0
2014/12/21    0
2014/12/22    0
2014/12/23    0
2014/12/24    0
2014/12/25    0
2014/12/26    0
2014/12/27    0
2014/12/28    0
2014/12/29    0
2014/12/3     0
2014/12/30    0
2014/12/31    0
2014/12/4     0
2014/12/5     0
2014/12/6     0
2014/12/7     0
2014/12/8     0
2014/12/9     0
2014/2/1      0
2014/2/10     0
2014/2/11     0
2014/2/12     0
2014/2/13     0
2014/2/14     0
2014/2/15     0
2014/2/16     0
2014/2/17     0
2014/2/18     0
2014/2/19     0
2014/2/2      0
2014/2/20     0
2014/2/21     0
2014/2/22     0
2014/2/23     0
2014/2/24     0
2014/2/25     0
2014/2/26     0
2014/2/27     0
2014/2/28     0
2014/2/3      0
2014/2/4      0
2014/2/5      0
2014/2/6      0
2014/2/7      0
2014/2/8      0
2014/2/9      0
2014/3/1      0
2014/3/10     0
2014/3/11     0
2014/3/12     0
2014/3/13     0
2014/3/14     0
2014/3/15     0
2014/3/16     0
2014/3/17     0
2014/3/18     0
2014/3/19     0
2014/3/2      0
2014/3/20     0
2014/3/21     0
2014/3/22     0
2014/3/23     0
2014/3/24     0
2014/3/25     0
2014/3/26     0
2014/3/27     0
2014/3/28     0
2014/3/29     0
2014/3/3      0
2014/3/30     0
2014/3/31     0
2014/3/4      0
2014/3/5      0
2014/3/6      0
2014/3/7      0
2014/3/8      0
2014/3/9      0
2014/4/1      0
2014/4/10     0
2014/4/11     0
2014/4/12     0
2014/4/13     0
2014/4/14     0
2014/4/15     0
2014/4/16     0
2014/4/17     0
2014/4/18     0
2014/4/19     0
2014/4/2      0
2014/4/20     0
2014/4/21     0
2014/4/22     0
2014/4/23     0
2014/4/24     0
2014/4/25     0
2014/4/26     0
2014/4/27     0
2014/4/28     0
2014/4/29     0
2014/4/3      0
2014/4/30     0
2014/4/4      0
2014/4/5      0
2014/4/6      0
2014/4/7      0
2014/4/8      0
2014/4/9      0
2014/5/1      0
2014/5/10     0
2014/5/11     0
2014/5/12     0
2014/5/13     0
2014/5/14     0
2014/5/15     0
2014/5/16     0
2014/5/17     0
2014/5/18     0
2014/5/19     0
2014/5/2      0
2014/5/20     0
2014/5/21     0
2014/5/22     0
2014/5/23     0
2014/5/24     0
2014/5/25     0
2014/5/26     0
2014/5/27     0
2014/5/28     0
2014/5/29     0
2014/5/3      0
2014/5/30     0
2014/5/31     0
2014/5/4      0
2014/5/5      0
2014/5/6      0
2014/5/7      0
2014/5/8      0
2014/5/9      0
2014/6/1      0
2014/6/10     0
2014/6/11     0
2014/6/12     0
2014/6/13     0
2014/6/14     0
2014/6/15     0
2014/6/16     0
2014/6/17     0
2014/6/18     0
2014/6/19     0
2014/6/2      0
2014/6/20     0
2014/6/21     0
2014/6/22     0
2014/6/23     0
2014/6/24     0
2014/6/25     0
2014/6/26     0
2014/6/27     0
2014/6/28     0
2014/6/29     0
2014/6/3      0
2014/6/30     0
2014/6/4      0
2014/6/5      0
2014/6/6      0
2014/6/7      0
2014/6/8      0
2014/6/9      0
2014/7/1      0
2014/7/10     0
2014/7/11     0
2014/7/12     0
2014/7/13     0
2014/7/14     0
2014/7/15     0
2014/7/16     0
2014/7/17     0
2014/7/18     0
2014/7/19     0
2014/7/2      0
2014/7/20     0
2014/7/21     0
2014/7/22     0
2014/7/23     0
2014/7/24     0
2014/7/25     0
2014/7/26     0
2014/7/27     0
2014/7/28     0
2014/7/29     0
2014/7/3      0
2014/7/30     0
2014/7/31     0
2014/7/4      0
2014/7/5      0
2014/7/6      0
2014/7/7      0
2014/7/8      0
2014/7/9      0
2014/8/1      0
2014/8/10     0
2014/8/11     0
2014/8/12     0
2014/8/13     0
2014/8/14     0
2014/8/15     0
2014/8/16     0
2014/8/17     0
2014/8/18     0
2014/8/19     0
2014/8/2      0
2014/8/20     0
2014/8/21     0
2014/8/22     0
2014/8/23     0
2014/8/24     0
2014/8/25     0
2014/8/26     0
2014/8/27     0
2014/8/28     0
2014/8/29     0
2014/8/3      0
2014/8/30     0
2014/8/31     0
2014/8/4      0
2014/8/5      0
2014/8/6      0
2014/8/7      0
2014/8/8      0
2014/8/9      0
2014/9/1      0
2014/9/10     0
2014/9/11     0
2014/9/12     0
2014/9/13     0
2014/9/14     0
2014/9/15     0
2014/9/16     0
2014/9/17     0
2014/9/18     0
2014/9/19     0
2014/9/2      0
2014/9/20     0
2014/9/21     0
2014/9/22     0
2014/9/23     0
2014/9/24     0
2014/9/25     0
2014/9/26     0
2014/9/27     0
2014/9/28     0
2014/9/29     0
2014/9/3      0
2014/9/30     0
2014/9/4      0
2014/9/5      0
2014/9/6      0
2014/9/7      0
2014/9/8      0
2014/9/9      0
2015/1/1      0
2015/1/10     0
2015/1/11     0
2015/1/12     0
2015/1/13     0
2015/1/14     0
2015/1/15     0
2015/1/16     0
2015/1/17     0
2015/1/18     0
2015/1/19     0
2015/1/2      0
2015/1/20     0
2015/1/21     0
2015/1/22     0
2015/1/23     0
2015/1/24     0
2015/1/25     0
2015/1/26     0
2015/1/27     0
2015/1/28     0
2015/1/29     0
2015/1/3      0
2015/1/30     0
2015/1/31     0
2015/1/4      0
2015/1/5      0
2015/1/6      0
2015/1/7      0
2015/1/8      0
2015/1/9      0
2015/10/1     0
2015/10/10    0
2015/10/11    0
2015/10/12    0
2015/10/13    0
2015/10/14    0
2015/10/15    0
2015/10/16    0
2015/10/17    0
2015/10/18    0
2015/10/19    0
2015/10/2     0
2015/10/20    0
2015/10/21    0
2015/10/22    0
2015/10/23    0
2015/10/24    0
2015/10/25    0
2015/10/26    0
2015/10/27    0
2015/10/28    0
2015/10/29    0
2015/10/3     0
2015/10/30    0
2015/10/31    0
2015/10/4     0
2015/10/5     0
2015/10/6     0
2015/10/7     0
2015/10/8     0
2015/10/9     0
2015/11/1     0
2015/11/10    0
2015/11/11    0
2015/11/12    0
2015/11/13    0
2015/11/14    0
2015/11/15    0
2015/11/16    0
2015/11/17    0
2015/11/18    0
2015/11/19    0
2015/11/2     0
2015/11/20    0
2015/11/21    0
2015/11/22    0
2015/11/23    0
2015/11/24    0
2015/11/25    0
2015/11/26    0
2015/11/27    0
2015/11/28    0
2015/11/29    0
2015/11/3     0
2015/11/30    0
2015/11/4     0
2015/11/5     0
2015/11/6     0
2015/11/7     0
2015/11/8     0
2015/11/9     0
2015/12/1     0
2015/12/10    0
2015/12/11    0
2015/12/12    0
2015/12/13    0
2015/12/14    0
2015/12/15    0
2015/12/16    0
2015/12/17    0
2015/12/18    0
2015/12/19    0
2015/12/2     0
2015/12/20    0
2015/12/21    0
2015/12/22    0
2015/12/23    0
2015/12/24    0
2015/12/25    0
2015/12/26    0
2015/12/27    0
2015/12/28    0
2015/12/29    0
2015/12/3     0
2015/12/30    0
2015/12/31    0
2015/12/4     0
2015/12/5     0
2015/12/6     0
2015/12/7     0
2015/12/8     0
2015/12/9     0
2015/2/1      0
2015/2/10     0
2015/2/11     0
2015/2/12     0
2015/2/13     0
2015/2/14     0
2015/2/15     0
2015/2/16     0
2015/2/17     0
2015/2/18     0
2015/2/19     0
2015/2/2      0
2015/2/20     0
2015/2/21     0
2015/2/22     0
2015/2/23     0
2015/2/24     0
2015/2/25     0
2015/2/26     0
2015/2/27     0
2015/2/28     0
2015/2/3      0
2015/2/4      0
2015/2/5      0
2015/2/6      0
2015/2/7      0
2015/2/8      0
2015/2/9      0
2015/3/1      0
2015/3/10     0
2015/3/11     0
2015/3/12     0
2015/3/13     0
2015/3/14     0
2015/3/15     0
2015/3/16     0
2015/3/17     0
2015/3/18     0
2015/3/19     0
2015/3/2      0
2015/3/20     0
2015/3/21     0
2015/3/22     0
2015/3/23     0
2015/3/24     0
2015/3/25     0
2015/3/26     0
2015/3/27     0
2015/3/28     0
2015/3/29     0
2015/3/3      0
2015/3/30     0
2015/3/31     0
2015/3/4      0
2015/3/5      0
2015/3/6      0
2015/3/7      0
2015/3/8      0
2015/3/9      0
2015/4/1      0
2015/4/10     0
2015/4/11     0
2015/4/12     0
2015/4/13     0
2015/4/14     0
2015/4/15     0
2015/4/16     0
2015/4/17     0
2015/4/18     0
2015/4/19     0
2015/4/2      0
2015/4/20     0
2015/4/21     0
2015/4/22     0
2015/4/23     0
2015/4/24     0
2015/4/25     0
2015/4/26     0
2015/4/27     0
2015/4/28     0
2015/4/29     0
2015/4/3      0
2015/4/30     0
2015/4/4      0
2015/4/5      0
2015/4/6      0
2015/4/7      0
2015/4/8      0
2015/4/9      0
2015/5/1      0
2015/5/10     0
2015/5/11     0
2015/5/12     0
2015/5/13     0
2015/5/14     0
2015/5/15     0
2015/5/16     0
2015/5/17     0
2015/5/18     0
2015/5/19     0
2015/5/2      0
2015/5/20     0
2015/5/21     0
2015/5/22     0
2015/5/23     0
2015/5/24     0
2015/5/25     0
2015/5/26     0
2015/5/27     0
2015/5/28     0
2015/5/29     0
2015/5/3      0
2015/5/30     0
2015/5/31     0
2015/5/4      0
2015/5/5      0
2015/5/6      0
2015/5/7      0
2015/5/8      0
2015/5/9      0
2015/6/1      0
2015/6/10     0
2015/6/11     0
2015/6/12     0
2015/6/13     0
2015/6/14     0
2015/6/15     0
2015/6/16     0
2015/6/17     0
2015/6/18     0
2015/6/19     0
2015/6/2      0
2015/6/20     0
2015/6/21     0
2015/6/22     0
2015/6/23     0
2015/6/24     0
2015/6/25     0
2015/6/26     0
2015/6/27     0
2015/6/28     0
2015/6/29     0
2015/6/3      0
2015/6/30     0
2015/6/4      0
2015/6/5      0
2015/6/6      0
2015/6/7      0
2015/6/8      0
2015/6/9      0
2015/7/1      0
2015/7/10     0
2015/7/11     0
2015/7/12     0
2015/7/13     0
2015/7/14     0
2015/7/15     0
2015/7/16     0
2015/7/17     0
2015/7/18     0
2015/7/19     0
2015/7/2      0
2015/7/20     0
2015/7/21     0
2015/7/22     0
2015/7/23     0
2015/7/24     0
2015/7/25     0
2015/7/26     0
2015/7/27     0
2015/7/28     0
2015/7/29     0
2015/7/3      0
2015/7/30     0
2015/7/31     0
2015/7/4      0
2015/7/5      0
2015/7/6      0
2015/7/7      0
2015/7/8      0
2015/7/9      0
2015/8/1      0
2015/8/10     0
2015/8/11     0
2015/8/12     0
2015/8/13     0
2015/8/14     0
2015/8/15     0
2015/8/16     0
2015/8/17     0
2015/8/18     0
2015/8/19     0
2015/8/2      0
2015/8/20     0
2015/8/21     0
2015/8/22     0
2015/8/23     0
2015/8/24     0
2015/8/25     0
2015/8/26     0
2015/8/27     0
2015/8/28     0
2015/8/29     0
2015/8/3      0
2015/8/30     0
2015/8/31     0
2015/8/4      0
2015/8/5      0
2015/8/6      0
2015/8/7      0
2015/8/8      0
2015/8/9      0
2015/9/1      0
2015/9/10     0
2015/9/11     0
2015/9/12     0
2015/9/13     0
2015/9/14     0
2015/9/15     0
2015/9/16     0
2015/9/17     0
2015/9/18     0
2015/9/19     0
2015/9/2      0
2015/9/20     0
2015/9/21     0
2015/9/22     0
2015/9/23     0
2015/9/24     0
2015/9/25     0
2015/9/26     0
2015/9/27     0
2015/9/28     0
2015/9/29     0
2015/9/3      0
2015/9/30     0
2015/9/4      0
2015/9/5      0
2015/9/6      0
2015/9/7      0
2015/9/8      0
2015/9/9      0
2016/1/1      0
2016/1/10     0
2016/1/11     0
2016/1/12     0
2016/1/13     0
2016/1/14     0
2016/1/15     0
2016/1/16     0
2016/1/17     0
2016/1/18     0
2016/1/19     0
2016/1/2      0
2016/1/20     0
2016/1/21     0
2016/1/22     0
2016/1/23     0
2016/1/24     0
2016/1/25     0
2016/1/26     0
2016/1/27     0
2016/1/28     0
2016/1/29     0
2016/1/3      0
2016/1/30     0
2016/1/31     0
2016/1/4      0
2016/1/5      0
2016/1/6      0
2016/1/7      0
2016/1/8      0
2016/1/9      0
2016/10/1     0
2016/10/10    0
2016/10/11    0
2016/10/12    0
2016/10/13    0
2016/10/14    0
2016/10/15    0
2016/10/16    0
2016/10/17    0
2016/10/18    0
2016/10/19    0
2016/10/2     0
2016/10/20    0
2016/10/21    0
2016/10/22    0
2016/10/23    0
2016/10/24    0
2016/10/25    0
2016/10/26    0
2016/10/27    0
2016/10/28    0
2016/10/29    0
2016/10/3     0
2016/10/30    0
2016/10/31    0
2016/10/4     0
2016/10/5     0
2016/10/6     0
2016/10/7     0
2016/10/8     0
2016/10/9     0
2016/2/1      0
2016/2/10     0
2016/2/11     0
2016/2/12     0
2016/2/13     0
2016/2/14     0
2016/2/15     0
2016/2/16     0
2016/2/17     0
2016/2/18     0
2016/2/19     0
2016/2/2      0
2016/2/20     0
2016/2/21     0
2016/2/22     0
2016/2/23     0
2016/2/24     0
2016/2/25     0
2016/2/26     0
2016/2/27     0
2016/2/28     0
2016/2/29     0
2016/2/3      0
2016/2/4      0
2016/2/5      0
2016/2/6      0
2016/2/7      0
2016/2/8      0
2016/2/9      0
2016/3/1      0
2016/3/10     0
2016/3/11     0
2016/3/12     0
2016/3/13     0
2016/3/14     0
2016/3/15     0
2016/3/16     0
2016/3/17     0
2016/3/18     0
2016/3/19     0
2016/3/2      0
2016/3/20     0
2016/3/21     0
2016/3/22     0
2016/3/23     0
2016/3/24     0
2016/3/25     0
2016/3/26     0
2016/3/27     0
2016/3/28     0
2016/3/29     0
2016/3/3      0
2016/3/30     0
2016/3/31     0
2016/3/4      0
2016/3/5      0
2016/3/6      0
2016/3/7      0
2016/3/8      0
2016/3/9      0
2016/4/1      0
2016/4/10     0
2016/4/11     0
2016/4/12     0
2016/4/13     0
2016/4/14     0
2016/4/15     0
2016/4/16     0
2016/4/17     0
2016/4/18     0
2016/4/19     0
2016/4/2      0
2016/4/20     0
2016/4/21     0
2016/4/22     0
2016/4/23     0
2016/4/24     0
2016/4/25     0
2016/4/26     0
2016/4/27     0
2016/4/28     0
2016/4/29     0
2016/4/3      0
2016/4/30     0
2016/4/4      0
2016/4/5      0
2016/4/6      0
2016/4/7      0
2016/4/8      0
2016/4/9      0
2016/5/1      0
2016/5/10     0
2016/5/11     0
2016/5/12     0
2016/5/13     0
2016/5/14     0
2016/5/15     0
2016/5/16     0
2016/5/17     0
2016/5/18     0
2016/5/19     0
2016/5/2      0
2016/5/20     0
2016/5/21     0
2016/5/22     0
2016/5/23     0
2016/5/24     0
2016/5/25     0
2016/5/26     0
2016/5/27     0
2016/5/28     0
2016/5/29     0
2016/5/3      0
2016/5/30     0
2016/5/31     0
2016/5/4      0
2016/5/5      0
2016/5/6      0
2016/5/7      0
2016/5/8      0
2016/5/9      0
2016/6/1      0
2016/6/10     0
2016/6/11     0
2016/6/12     0
2016/6/13     0
2016/6/14     0
2016/6/15     0
2016/6/16     0
2016/6/17     0
2016/6/18     0
2016/6/19     0
2016/6/2      0
2016/6/20     0
2016/6/21     0
2016/6/22     0
2016/6/23     0
2016/6/24     0
2016/6/25     0
2016/6/26     0
2016/6/27     0
2016/6/28     0
2016/6/29     0
2016/6/3      0
2016/6/30     0
2016/6/4      0
2016/6/5      0
2016/6/6      0
2016/6/7      0
2016/6/8      0
2016/6/9      0
2016/7/1      0
2016/7/10     0
2016/7/11     0
2016/7/12     0
2016/7/13     0
2016/7/14     0
2016/7/15     0
2016/7/16     0
2016/7/17     0
2016/7/18     0
2016/7/19     0
2016/7/2      0
2016/7/20     0
2016/7/21     0
2016/7/22     0
2016/7/23     0
2016/7/24     0
2016/7/25     0
2016/7/26     0
2016/7/27     0
2016/7/28     0
2016/7/29     0
2016/7/3      0
2016/7/30     0
2016/7/31     0
2016/7/4      0
2016/7/5      0
2016/7/6      0
2016/7/7      0
2016/7/8      0
2016/7/9      0
2016/8/1      0
2016/8/10     0
2016/8/11     0
2016/8/12     0
2016/8/13     0
2016/8/14     0
2016/8/15     0
2016/8/16     0
2016/8/17     0
2016/8/18     0
2016/8/19     0
2016/8/2      0
2016/8/20     0
2016/8/21     0
2016/8/22     0
2016/8/23     0
2016/8/24     0
2016/8/25     0
2016/8/26     0
2016/8/27     0
2016/8/28     0
2016/8/29     0
2016/8/3      0
2016/8/30     0
2016/8/31     0
2016/8/4      0
2016/8/5      0
2016/8/6      0
2016/8/7      0
2016/8/8      0
2016/8/9      0
2016/9/1      0
2016/9/10     0
2016/9/11     0
2016/9/12     0
2016/9/13     0
2016/9/14     0
2016/9/15     0
2016/9/16     0
2016/9/17     0
2016/9/19     0
2016/9/2      0
2016/9/20     0
2016/9/21     0
2016/9/22     0
2016/9/23     0
2016/9/24     0
2016/9/25     0
2016/9/26     0
2016/9/27     0
2016/9/28     0
2016/9/29     0
2016/9/3      0
2016/9/30     0
2016/9/4      0
2016/9/5      0
2016/9/6      0
2016/9/7      0
2016/9/8      0
2016/9/9      0
FLAG          0
dtype: int64

In [40]:
df = df_final.copy()

In [41]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,FLAG
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,9.96000,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000,1.0
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.0
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,1.0
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,9.99000,11.78000,18.59000,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000,1.0
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,10.37000,15.32000,13.51000,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000,1.0

In [42]:
date_columns = [col for col in df.columns if col not in ['FLAG']]

In [43]:
df['mean_consumption'] = df[date_columns].mean(axis=1)

In [44]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,FLAG,mean_consumption
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000,1.0,13.898342
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.0,0.000000
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,1.0,9.921390
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,11.78000,18.59000,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000,1.0,14.612055
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,15.32000,13.51000,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000,1.0,8.249738

In [45]:
df['std_consumption'] = df[date_columns].std(axis=1)
import warnings
warnings.filterwarnings("ignore", message="DataFrame is highly fragmented")
df['cv'] = df['std_consumption'] / (df['mean_consumption'] + 1e-10)

In [46]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,FLAG,mean_consumption,std_consumption,cv
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000,1.0,13.898342,6.683785,0.480905
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.0,0.000000,0.000000,0.000000
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,9.92139,1.0,9.921390,3.409611,0.343663
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,26.80000,18.57000,14.59000,12.82000,19.37000,15.92000,1.0,14.612055,7.712976,0.527850
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,12.23000,14.68000,16.35000,18.14000,18.41000,17.31000,1.0,8.249738,5.930837,0.718912

In [47]:
df['num_zeros'] = (df[date_columns] == 0).sum(axis=1)

In [48]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,FLAG,mean_consumption,std_consumption,cv,num_zeros
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,18.05000,26.47000,18.75000,17.84000,14.92000,1.0,13.898342,6.683785,0.480905,0
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.00000,1.0,0.000000,0.000000,0.000000,1034
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,9.92139,1.0,9.921390,3.409611,0.343663,41
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,18.57000,14.59000,12.82000,19.37000,15.92000,1.0,14.612055,7.712976,0.527850,0
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,14.68000,16.35000,18.14000,18.41000,17.31000,1.0,8.249738,5.930837,0.718912,0

In [49]:
import numpy as np
# 5. Trend Slope
def calculate_trend(row):
    x = np.arange(len(row))
    y = row.values
    if np.std(y) == 0:
        return 0
    slope = np.polyfit(x, y, 1)[0]
    return slope
df['trend_slope'] = df[date_columns].apply(calculate_trend, axis=1)

In [50]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,2016/9/6,2016/9/7,2016/9/8,2016/9/9,FLAG,mean_consumption,std_consumption,cv,num_zeros,trend_slope
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,26.47000,18.75000,17.84000,14.92000,1.0,13.898342,6.683785,0.480905,0,-0.000364
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,1.0,0.000000,0.000000,0.000000,1034,0.000000
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,9.92139,9.92139,9.92139,9.92139,1.0,9.921390,3.409611,0.343663,41,-0.000358
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,14.59000,12.82000,19.37000,15.92000,1.0,14.612055,7.712976,0.527850,0,0.012225
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,16.35000,18.14000,18.41000,17.31000,1.0,8.249738,5.930837,0.718912,0,0.010040

In [51]:
# 6. Max Drop Percentage
pct_changes = df[date_columns].pct_change(axis=1)
df['max_drop_pct'] = pct_changes.min(axis=1).abs()

In [52]:
# 7. Sudden Drop Count (drops > 50% of mean)
drops = df[date_columns].diff(axis=1)
df['sudden_drop_count'] = (drops < -df['mean_consumption'].values[:, None] * 0.5).sum(axis=1)

In [53]:
# 8. Minimum Consumption
df['min_consumption'] = df[date_columns].min(axis=1)

In [54]:
df['max_consumption'] = df[date_columns].max(axis=1)

In [55]:
df['median_consumption'] = df[date_columns].median(axis=1)

In [56]:
df['num_below_mean'] = df[date_columns].lt(df['mean_consumption'], axis=0).sum(axis=1)

In [57]:
df['skewness'] = df[date_columns].skew(axis=1)

In [58]:
df['iqr'] = df[date_columns].quantile(0.75, axis=1) - df[date_columns].quantile(0.25, axis=1)

In [59]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,num_zeros,trend_slope,max_drop_pct,sudden_drop_count,min_consumption,max_consumption,median_consumption,num_below_mean,skewness,iqr
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,0,-0.000364,0.926731,46,2.46,46.49,13.898342,811,1.513367,5.095842
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1034,0.000000,NaN,0,0.00,0.00,0.000000,0,0.000000,0.000000
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,41,-0.000358,1.000000,15,0.00,32.81,9.921390,160,1.976875,0.000000
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,0,0.012225,0.992418,56,0.40,52.76,14.612055,266,0.984226,0.399555
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,0,0.010040,0.750733,51,0.85,43.43,6.280000,694,2.597712,5.197500

In [60]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

2014/1/1                 0
2014/1/10                0
2014/1/11                0
2014/1/12                0
2014/1/13                0
2014/1/14                0
2014/1/15                0
2014/1/16                0
2014/1/17                0
2014/1/18                0
2014/1/19                0
2014/1/2                 0
2014/1/20                0
2014/1/21                0
2014/1/22                0
2014/1/23                0
2014/1/24                0
2014/1/25                0
2014/1/26                0
2014/1/27                0
2014/1/28                0
2014/1/29                0
2014/1/3                 0
2014/1/30                0
2014/1/31                0
2014/1/4                 0
2014/1/5                 0
2014/1/6                 0
2014/1/7                 0
2014/1/8                 0
2014/1/9                 0
2014/10/1                0
2014/10/10               0
2014/10/11               0
2014/10/12               0
2014/10/13               0
2014/10/14               0
2014/10/15               0
2014/10/16               0
2014/10/17               0
2014/10/18               0
2014/10/19               0
2014/10/2                0
2014/10/20               0
2014/10/21               0
2014/10/22               0
2014/10/23               0
2014/10/24               0
2014/10/25               0
2014/10/26               0
2014/10/27               0
2014/10/28               0
2014/10/29               0
2014/10/3                0
2014/10/30               0
2014/10/31               0
2014/10/4                0
2014/10/5                0
2014/10/6                0
2014/10/7                0
2014/10/8                0
2014/10/9                0
2014/11/1                0
2014/11/10               0
2014/11/11               0
2014/11/12               0
2014/11/13               0
2014/11/14               0
2014/11/15               0
2014/11/16               0
2014/11/17               0
2014/11/18               0
2014/11/19               0
2014/11/2                0
2014/11/20               0
2014/11/21               0
2014/11/22               0
2014/11/23               0
2014/11/24               0
2014/11/25               0
2014/11/26               0
2014/11/27               0
2014/11/28               0
2014/11/29               0
2014/11/3                0
2014/11/30               0
2014/11/4                0
2014/11/5                0
2014/11/6                0
2014/11/7                0
2014/11/8                0
2014/11/9                0
2014/12/1                0
2014/12/10               0
2014/12/11               0
2014/12/12               0
2014/12/13               0
2014/12/14               0
2014/12/15               0
2014/12/16               0
2014/12/17               0
2014/12/18               0
2014/12/19               0
2014/12/2                0
2014/12/20               0
2014/12/21               0
2014/12/22               0
2014/12/23               0
2014/12/24               0
2014/12/25               0
2014/12/26               0
2014/12/27               0
2014/12/28               0
2014/12/29               0
2014/12/3                0
2014/12/30               0
2014/12/31               0
2014/12/4                0
2014/12/5                0
2014/12/6                0
2014/12/7                0
2014/12/8                0
2014/12/9                0
2014/2/1                 0
2014/2/10                0
2014/2/11                0
2014/2/12                0
2014/2/13                0
2014/2/14                0
2014/2/15                0
2014/2/16                0
2014/2/17                0
2014/2/18                0
2014/2/19                0
2014/2/2                 0
2014/2/20                0
2014/2/21                0
2014/2/22                0
2014/2/23                0
2014/2/24                0
2014/2/25                0
2014/2/26                0
2014/2/27                0
2014/2/28                0
2014/2/3                 0
2014/2/4                 0
2014/2/5                 0
2014/2/6                 0
2014/2/7                 0
2014/2/8                 0
2014/2/9                 0
2014/3/1                 0
2014/3/10                0
2014/3/11                0
2014/3/12                0
2014/3/13                0
2014/3/14                0
2014/3/15                0
2014/3/16                0
2014/3/17                0
2014/3/18                0
2014/3/19                0
2014/3/2                 0
2014/3/20                0
2014/3/21                0
2014/3/22                0
2014/3/23                0
2014/3/24                0
2014/3/25                0
2014/3/26                0
2014/3/27                0
2014/3/28                0
2014/3/29                0
2014/3/3                 0
2014/3/30                0
2014/3/31                0
2014/3/4                 0
2014/3/5                 0
2014/3/6                 0
2014/3/7                 0
2014/3/8                 0
2014/3/9                 0
2014/4/1                 0
2014/4/10                0
2014/4/11                0
2014/4/12                0
2014/4/13                0
2014/4/14                0
2014/4/15                0
2014/4/16                0
2014/4/17                0
2014/4/18                0
2014/4/19                0
2014/4/2                 0
2014/4/20                0
2014/4/21                0
2014/4/22                0
2014/4/23                0
2014/4/24                0
2014/4/25                0
2014/4/26                0
2014/4/27                0
2014/4/28                0
2014/4/29                0
2014/4/3                 0
2014/4/30                0
2014/4/4                 0
2014/4/5                 0
2014/4/6                 0
2014/4/7                 0
2014/4/8                 0
2014/4/9                 0
2014/5/1                 0
2014/5/10                0
2014/5/11                0
2014/5/12                0
2014/5/13                0
2014/5/14                0
2014/5/15                0
2014/5/16                0
2014/5/17                0
2014/5/18                0
2014/5/19                0
2014/5/2                 0
2014/5/20                0
2014/5/21                0
2014/5/22                0
2014/5/23                0
2014/5/24                0
2014/5/25                0
2014/5/26                0
2014/5/27                0
2014/5/28                0
2014/5/29                0
2014/5/3                 0
2014/5/30                0
2014/5/31                0
2014/5/4                 0
2014/5/5                 0
2014/5/6                 0
2014/5/7                 0
2014/5/8                 0
2014/5/9                 0
2014/6/1                 0
2014/6/10                0
2014/6/11                0
2014/6/12                0
2014/6/13                0
2014/6/14                0
2014/6/15                0
2014/6/16                0
2014/6/17                0
2014/6/18                0
2014/6/19                0
2014/6/2                 0
2014/6/20                0
2014/6/21                0
2014/6/22                0
2014/6/23                0
2014/6/24                0
2014/6/25                0
2014/6/26                0
2014/6/27                0
2014/6/28                0
2014/6/29                0
2014/6/3                 0
2014/6/30                0
2014/6/4                 0
2014/6/5                 0
2014/6/6                 0
2014/6/7                 0
2014/6/8                 0
2014/6/9                 0
2014/7/1                 0
2014/7/10                0
2014/7/11                0
2014/7/12                0
2014/7/13                0
2014/7/14                0
2014/7/15                0
2014/7/16                0
2014/7/17                0
2014/7/18                0
2014/7/19                0
2014/7/2                 0
2014/7/20                0
2014/7/21                0
2014/7/22                0
2014/7/23                0
2014/7/24                0
2014/7/25                0
2014/7/26                0
2014/7/27                0
2014/7/28                0
2014/7/29                0
2014/7/3                 0
2014/7/30                0
2014/7/31                0
2014/7/4                 0
2014/7/5                 0
2014/7/6                 0
2014/7/7                 0
2014/7/8                 0
2014/7/9                 0
2014/8/1                 0
2014/8/10                0
2014/8/11                0
2014/8/12                0
2014/8/13                0
2014/8/14                0
2014/8/15                0
2014/8/16                0
2014/8/17                0
2014/8/18                0
2014/8/19                0
2014/8/2                 0
2014/8/20                0
2014/8/21                0
2014/8/22                0
2014/8/23                0
2014/8/24                0
2014/8/25                0
2014/8/26                0
2014/8/27                0
2014/8/28                0
2014/8/29                0
2014/8/3                 0
2014/8/30                0
2014/8/31                0
2014/8/4                 0
2014/8/5                 0
2014/8/6                 0
2014/8/7                 0
2014/8/8                 0
2014/8/9                 0
2014/9/1                 0
2014/9/10                0
2014/9/11                0
2014/9/12                0
2014/9/13                0
2014/9/14                0
2014/9/15                0
2014/9/16                0
2014/9/17                0
2014/9/18                0
2014/9/19                0
2014/9/2                 0
2014/9/20                0
2014/9/21                0
2014/9/22                0
2014/9/23                0
2014/9/24                0
2014/9/25                0
2014/9/26                0
2014/9/27                0
2014/9/28                0
2014/9/29                0
2014/9/3                 0
2014/9/30                0
2014/9/4                 0
2014/9/5                 0
2014/9/6                 0
2014/9/7                 0
2014/9/8                 0
2014/9/9                 0
2015/1/1                 0
2015/1/10                0
2015/1/11                0
2015/1/12                0
2015/1/13                0
2015/1/14                0
2015/1/15                0
2015/1/16                0
2015/1/17                0
2015/1/18                0
2015/1/19                0
2015/1/2                 0
2015/1/20                0
2015/1/21                0
2015/1/22                0
2015/1/23                0
2015/1/24                0
2015/1/25                0
2015/1/26                0
2015/1/27                0
2015/1/28                0
2015/1/29                0
2015/1/3                 0
2015/1/30                0
2015/1/31                0
2015/1/4                 0
2015/1/5                 0
2015/1/6                 0
2015/1/7                 0
2015/1/8                 0
2015/1/9                 0
2015/10/1                0
2015/10/10               0
2015/10/11               0
2015/10/12               0
2015/10/13               0
2015/10/14               0
2015/10/15               0
2015/10/16               0
2015/10/17               0
2015/10/18               0
2015/10/19               0
2015/10/2                0
2015/10/20               0
2015/10/21               0
2015/10/22               0
2015/10/23               0
2015/10/24               0
2015/10/25               0
2015/10/26               0
2015/10/27               0
2015/10/28               0
2015/10/29               0
2015/10/3                0
2015/10/30               0
2015/10/31               0
2015/10/4                0
2015/10/5                0
2015/10/6                0
2015/10/7                0
2015/10/8                0
2015/10/9                0
2015/11/1                0
2015/11/10               0
2015/11/11               0
2015/11/12               0
2015/11/13               0
2015/11/14               0
2015/11/15               0
2015/11/16               0
2015/11/17               0
2015/11/18               0
2015/11/19               0
2015/11/2                0
2015/11/20               0
2015/11/21               0
2015/11/22               0
2015/11/23               0
2015/11/24               0
2015/11/25               0
2015/11/26               0
2015/11/27               0
2015/11/28               0
2015/11/29               0
2015/11/3                0
2015/11/30               0
2015/11/4                0
2015/11/5                0
2015/11/6                0
2015/11/7                0
2015/11/8                0
2015/11/9                0
2015/12/1                0
2015/12/10               0
2015/12/11               0
2015/12/12               0
2015/12/13               0
2015/12/14               0
2015/12/15               0
2015/12/16               0
2015/12/17               0
2015/12/18               0
2015/12/19               0
2015/12/2                0
2015/12/20               0
2015/12/21               0
2015/12/22               0
2015/12/23               0
2015/12/24               0
2015/12/25               0
2015/12/26               0
2015/12/27               0
2015/12/28               0
2015/12/29               0
2015/12/3                0
2015/12/30               0
2015/12/31               0
2015/12/4                0
2015/12/5                0
2015/12/6                0
2015/12/7                0
2015/12/8                0
2015/12/9                0
2015/2/1                 0
2015/2/10                0
2015/2/11                0
2015/2/12                0
2015/2/13                0
2015/2/14                0
2015/2/15                0
2015/2/16                0
2015/2/17                0
2015/2/18                0
2015/2/19                0
2015/2/2                 0
2015/2/20                0
2015/2/21                0
2015/2/22                0
2015/2/23                0
2015/2/24                0
2015/2/25                0
2015/2/26                0
2015/2/27                0
2015/2/28                0
2015/2/3                 0
2015/2/4                 0
2015/2/5                 0
2015/2/6                 0
2015/2/7                 0
2015/2/8                 0
2015/2/9                 0
2015/3/1                 0
2015/3/10                0
2015/3/11                0
2015/3/12                0
2015/3/13                0
2015/3/14                0
2015/3/15                0
2015/3/16                0
2015/3/17                0
2015/3/18                0
2015/3/19                0
2015/3/2                 0
2015/3/20                0
2015/3/21                0
2015/3/22                0
2015/3/23                0
2015/3/24                0
2015/3/25                0
2015/3/26                0
2015/3/27                0
2015/3/28                0
2015/3/29                0
2015/3/3                 0
2015/3/30                0
2015/3/31                0
2015/3/4                 0
2015/3/5                 0
2015/3/6                 0
2015/3/7                 0
2015/3/8                 0
2015/3/9                 0
2015/4/1                 0
2015/4/10                0
2015/4/11                0
2015/4/12                0
2015/4/13                0
2015/4/14                0
2015/4/15                0
2015/4/16                0
2015/4/17                0
2015/4/18                0
2015/4/19                0
2015/4/2                 0
2015/4/20                0
2015/4/21                0
2015/4/22                0
2015/4/23                0
2015/4/24                0
2015/4/25                0
2015/4/26                0
2015/4/27                0
2015/4/28                0
2015/4/29                0
2015/4/3                 0
2015/4/30                0
2015/4/4                 0
2015/4/5                 0
2015/4/6                 0
2015/4/7                 0
2015/4/8                 0
2015/4/9                 0
2015/5/1                 0
2015/5/10                0
2015/5/11                0
2015/5/12                0
2015/5/13                0
2015/5/14                0
2015/5/15                0
2015/5/16                0
2015/5/17                0
2015/5/18                0
2015/5/19                0
2015/5/2                 0
2015/5/20                0
2015/5/21                0
2015/5/22                0
2015/5/23                0
2015/5/24                0
2015/5/25                0
2015/5/26                0
2015/5/27                0
2015/5/28                0
2015/5/29                0
2015/5/3                 0
2015/5/30                0
2015/5/31                0
2015/5/4                 0
2015/5/5                 0
2015/5/6                 0
2015/5/7                 0
2015/5/8                 0
2015/5/9                 0
2015/6/1                 0
2015/6/10                0
2015/6/11                0
2015/6/12                0
2015/6/13                0
2015/6/14                0
2015/6/15                0
2015/6/16                0
2015/6/17                0
2015/6/18                0
2015/6/19                0
2015/6/2                 0
2015/6/20                0
2015/6/21                0
2015/6/22                0
2015/6/23                0
2015/6/24                0
2015/6/25                0
2015/6/26                0
2015/6/27                0
2015/6/28                0
2015/6/29                0
2015/6/3                 0
2015/6/30                0
2015/6/4                 0
2015/6/5                 0
2015/6/6                 0
2015/6/7                 0
2015/6/8                 0
2015/6/9                 0
2015/7/1                 0
2015/7/10                0
2015/7/11                0
2015/7/12                0
2015/7/13                0
2015/7/14                0
2015/7/15                0
2015/7/16                0
2015/7/17                0
2015/7/18                0
2015/7/19                0
2015/7/2                 0
2015/7/20                0
2015/7/21                0
2015/7/22                0
2015/7/23                0
2015/7/24                0
2015/7/25                0
2015/7/26                0
2015/7/27                0
2015/7/28                0
2015/7/29                0
2015/7/3                 0
2015/7/30                0
2015/7/31                0
2015/7/4                 0
2015/7/5                 0
2015/7/6                 0
2015/7/7                 0
2015/7/8                 0
2015/7/9                 0
2015/8/1                 0
2015/8/10                0
2015/8/11                0
2015/8/12                0
2015/8/13                0
2015/8/14                0
2015/8/15                0
2015/8/16                0
2015/8/17                0
2015/8/18                0
2015/8/19                0
2015/8/2                 0
2015/8/20                0
2015/8/21                0
2015/8/22                0
2015/8/23                0
2015/8/24                0
2015/8/25                0
2015/8/26                0
2015/8/27                0
2015/8/28                0
2015/8/29                0
2015/8/3                 0
2015/8/30                0
2015/8/31                0
2015/8/4                 0
2015/8/5                 0
2015/8/6                 0
2015/8/7                 0
2015/8/8                 0
2015/8/9                 0
2015/9/1                 0
2015/9/10                0
2015/9/11                0
2015/9/12                0
2015/9/13                0
2015/9/14                0
2015/9/15                0
2015/9/16                0
2015/9/17                0
2015/9/18                0
2015/9/19                0
2015/9/2                 0
2015/9/20                0
2015/9/21                0
2015/9/22                0
2015/9/23                0
2015/9/24                0
2015/9/25                0
2015/9/26                0
2015/9/27                0
2015/9/28                0
2015/9/29                0
2015/9/3                 0
2015/9/30                0
2015/9/4                 0
2015/9/5                 0
2015/9/6                 0
2015/9/7                 0
2015/9/8                 0
2015/9/9                 0
2016/1/1                 0
2016/1/10                0
2016/1/11                0
2016/1/12                0
2016/1/13                0
2016/1/14                0
2016/1/15                0
2016/1/16                0
2016/1/17                0
2016/1/18                0

In [61]:
df = df.drop(columns=['max_drop_pct'])

In [62]:
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,...,cv,num_zeros,trend_slope,sudden_drop_count,min_consumption,max_consumption,median_consumption,num_below_mean,skewness,iqr
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,...,0.480905,0,-0.000364,46,2.46,46.49,13.898342,811,1.513367,5.095842
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1034,0.000000,0,0.00,0.00,0.000000,0,0.000000,0.000000
2,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,9.921390,...,0.343663,41,-0.000358,15,0.00,32.81,9.921390,160,1.976875,0.000000
3,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,14.612055,...,0.527850,0,0.012225,56,0.40,52.76,14.612055,266,0.984226,0.399555
4,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,0.850000,...,0.718912,0,0.010040,51,0.85,43.43,6.280000,694,2.597712,5.197500

In [63]:
# Calculate percentage changes
pct_changes = df[date_columns].pct_change(axis=1)

# Replace infinity values with 0
pct_changes = pct_changes.replace([np.inf, -np.inf], 0)

# Replace NaN with 0
pct_changes = pct_changes.fillna(0)

# Get max drop percentage
df['max_drop_pct'] = pct_changes.min(axis=1).abs()

# Final check - ensure no NULL values remain
df['max_drop_pct'] = df['max_drop_pct'].fillna(0)

In [64]:
pd.set_option('display.max_columns', None)
df.head()

,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,2014/1/18,2014/1/19,2014/1/2,2014/1/20,2014/1/21,2014/1/22,2014/1/23,2014/1/24,2014/1/25,2014/1/26,2014/1/27,2014/1/28,2014/1/29,2014/1/3,2014/1/30,2014/1/31,2014/1/4,2014/1/5,2014/1/6,2014/1/7,2014/1/8,2014/1/9,2014/10/1,2014/10/10,2014/10/11,2014/10/12,2014/10/13,2014/10/14,2014/10/15,2014/10/16,2014/10/17,2014/10/18,2014/10/19,2014/10/2,2014/10/20,2014/10/21,2014/10/22,2014/10/23,2014/10/24,2014/10/25,2014/10/26,2014/10/27,2014/10/28,2014/10/29,2014/10/3,2014/10/30,2014/10/31,2014/10/4,2014/10/5,2014/10/6,2014/10/7,2014/10/8,2014/10/9,2014/11/1,2014/11/10,2014/11/11,2014/11/12,2014/11/13,2014/11/14,2014/11/15,2014/11/16,2014/11/17,2014/11/18,2014/11/19,2014/11/2,2014/11/20,2014/11/21,2014/11/22,2014/11/23,2014/11/24,2014/11/25,2014/11/26,2014/11/27,2014/11/28,2014/11/29,2014/11/3,2014/11/30,2014/11/4,2014/11/5,2014/11/6,2014/11/7,2014/11/8,2014/11/9,2014/12/1,2014/12/10,2014/12/11,2014/12/12,2014/12/13,2014/12/14,2014/12/15,2014/12/16,2014/12/17,2014/12/18,2014/12/19,2014/12/2,2014/12/20,2014/12/21,2014/12/22,2014/12/23,2014/12/24,2014/12/25,2014/12/26,2014/12/27,2014/12/28,2014/12/29,2014/12/3,2014/12/30,2014/12/31,2014/12/4,2014/12/5,2014/12/6,2014/12/7,2014/12/8,2014/12/9,2014/2/1,2014/2/10,2014/2/11,2014/2/12,2014/2/13,2014/2/14,2014/2/15,2014/2/16,2014/2/17,2014/2/18,2014/2/19,2014/2/2,2014/2/20,2014/2/21,2014/2/22,2014/2/23,2014/2/24,2014/2/25,2014/2/26,2014/2/27,2014/2/28,2014/2/3,2014/2/4,2014/2/5,2014/2/6,2014/2/7,2014/2/8,2014/2/9,2014/3/1,2014/3/10,2014/3/11,2014/3/12,2014/3/13,2014/3/14,2014/3/15,2014/3/16,2014/3/17,2014/3/18,2014/3/19,2014/3/2,2014/3/20,2014/3/21,2014/3/22,2014/3/23,2014/3/24,2014/3/25,2014/3/26,2014/3/27,2014/3/28,2014/3/29,2014/3/3,2014/3/30,2014/3/31,2014/3/4,2014/3/5,2014/3/6,2014/3/7,2014/3/8,2014/3/9,2014/4/1,2014/4/10,2014/4/11,2014/4/12,2014/4/13,2014/4/14,2014/4/15,2014/4/16,2014/4/17,2014/4/18,2014/4/19,2014/4/2,2014/4/20,2014/4/21,2014/4/22,2014/4/23,2014/4/24,2014/4/25,2014/4/26,2014/4/27,2014/4/28,2014/4/29,2014/4/3,2014/4/30,2014/4/4,2014/4/5,2014/4/6,2014/4/7,2014/4/8,2014/4/9,2014/5/1,2014/5/10,2014/5/11,2014/5/12,2014/5/13,2014/5/14,2014/5/15,2014/5/16,2014/5/17,2014/5/18,2014/5/19,2014/5/2,2014/5/20,2014/5/21,2014/5/22,2014/5/23,2014/5/24,2014/5/25,2014/5/26,2014/5/27,2014/5/28,2014/5/29,2014/5/3,2014/5/30,2014/5/31,2014/5/4,2014/5/5,2014/5/6,2014/5/7,2014/5/8,2014/5/9,2014/6/1,2014/6/10,2014/6/11,2014/6/12,2014/6/13,2014/6/14,2014/6/15,2014/6/16,2014/6/17,2014/6/18,2014/6/19,2014/6/2,2014/6/20,2014/6/21,2014/6/22,2014/6/23,2014/6/24,2014/6/25,2014/6/26,2014/6/27,2014/6/28,2014/6/29,2014/6/3,2014/6/30,2014/6/4,2014/6/5,2014/6/6,2014/6/7,2014/6/8,2014/6/9,2014/7/1,2014/7/10,2014/7/11,2014/7/12,2014/7/13,2014/7/14,2014/7/15,2014/7/16,2014/7/17,2014/7/18,2014/7/19,2014/7/2,2014/7/20,2014/7/21,2014/7/22,2014/7/23,2014/7/24,2014/7/25,2014/7/26,2014/7/27,2014/7/28,2014/7/29,2014/7/3,2014/7/30,2014/7/31,2014/7/4,2014/7/5,2014/7/6,2014/7/7,2014/7/8,2014/7/9,2014/8/1,2014/8/10,2014/8/11,2014/8/12,2014/8/13,2014/8/14,2014/8/15,2014/8/16,2014/8/17,2014/8/18,2014/8/19,2014/8/2,2014/8/20,2014/8/21,2014/8/22,2014/8/23,2014/8/24,2014/8/25,2014/8/26,2014/8/27,2014/8/28,2014/8/29,2014/8/3,2014/8/30,2014/8/31,2014/8/4,2014/8/5,2014/8/6,2014/8/7,2014/8/8,2014/8/9,2014/9/1,2014/9/10,2014/9/11,2014/9/12,2014/9/13,2014/9/14,2014/9/15,2014/9/16,2014/9/17,2014/9/18,2014/9/19,2014/9/2,2014/9/20,2014/9/21,2014/9/22,2014/9/23,2014/9/24,2014/9/25,2014/9/26,2014/9/27,2014/9/28,2014/9/29,2014/9/3,2014/9/30,2014/9/4,2014/9/5,2014/9/6,2014/9/7,2014/9/8,2014/9/9,2015/1/1,2015/1/10,2015/1/11,2015/1/12,2015/1/13,2015/1/14,2015/1/15,2015/1/16,2015/1/17,2015/1/18,2015/1/19,2015/1/2,2015/1/20,2015/1/21,2015/1/22,2015/1/23,2015/1/24,2015/1/25,2015/1/26,2015/1/27,2015/1/28,2015/1/29,2015/1/3,2015/1/30,2015/1/31,2015/1/4,2015/1/5,2015/1/6,2015/1/7,2015/1/8,2015/1/9,2015/10/1,2015/10/10,2015/10/11,2015/10/12,2015/10/13,2015/10/14,2015/10/15,2015/10/16,2015/10/17,2015/10/18,2015/10/19,2015/10/2,2015/10/20,2015/10/21,2015/10/22,2015/10/23,2015/10/24,2015/10/25,2015/10/26,2015/10/27,2015/10/28,2015/10/29,2015/10/3,2015/10/30,2015/10/31,2015/10/4,2015/10/5,2015/10/6,2015/10/7,2015/10/8,2015/10/9,2015/11/1,2015/11/10,2015/11/11,2015/11/12,2015/11/13,2015/11/14,2015/11/15,2015/11/16,2015/11/17,2015/11/18,2015/11/19,2015/11/2,2015/11/20,2015/11/21,2015/11/22,2015/11/23,2015/11/24,2015/11/25,2015/11/26,2015/11/27,2015/11/28,2015/11/29,2015/11/3,2015/11/30,2015/11/4,2015/11/5,2015/11/6,2015/11/7,2015/11/8,2015/11/9,2015/12/1,2015/12/10,2015/12/11,2015/12/12,2015/12/13,2015/12/14,2015/12/15,2015/12/16,2015/12/17,2015/12/18,2015/12/19,2015/12/2,2015/12/20,2015/12/21,2015/12/22,2015/12/23,2015/12/24,2015/12/25,2015/12/26,2015/12/27,2015/12/28,2015/12/29,2015/12/3,2015/12/30,2015/12/31,2015/12/4,2015/12/5,2015/12/6,2015/12/7,2015/12/8,2015/12/9,2015/2/1,2015/2/10,2015/2/11,2015/2/12,2015/2/13,2015/2/14,2015/2/15,2015/2/16,2015/2/17,2015/2/18,2015/2/19,2015/2/2,2015/2/20,2015/2/21,2015/2/22,2015/2/23,2015/2/24,2015/2/25,2015/2/26,2015/2/27,2015/2/28,2015/2/3,2015/2/4,2015/2/5,2015/2/6,2015/2/7,2015/2/8,2015/2/9,2015/3/1,2015/3/10,2015/3/11,2015/3/12,2015/3/13,2015/3/14,2015/3/15,2015/3/16,2015/3/17,2015/3/18,2015/3/19,2015/3/2,2015/3/20,2015/3/21,2015/3/22,2015/3/23,2015/3/24,2015/3/25,2015/3/26,2015/3/27,2015/3/28,2015/3/29,2015/3/3,2015/3/30,2015/3/31,2015/3/4,2015/3/5,2015/3/6,2015/3/7,2015/3/8,2015/3/9,2015/4/1,2015/4/10,2015/4/11,2015/4/12,2015/4/13,2015/4/14,2015/4/15,2015/4/16,2015/4/17,2015/4/18,2015/4/19,2015/4/2,2015/4/20,2015/4/21,2015/4/22,2015/4/23,2015/4/24,2015/4/25,2015/4/26,2015/4/27,2015/4/28,2015/4/29,2015/4/3,2015/4/30,2015/4/4,2015/4/5,2015/4/6,2015/4/7,2015/4/8,2015/4/9,2015/5/1,2015/5/10,2015/5/11,2015/5/12,2015/5/13,2015/5/14,2015/5/15,2015/5/16,2015/5/17,2015/5/18,2015/5/19,2015/5/2,2015/5/20,2015/5/21,2015/5/22,2015/5/23,2015/5/24,2015/5/25,2015/5/26,2015/5/27,2015/5/28,2015/5/29,2015/5/3,2015/5/30,2015/5/31,2015/5/4,2015/5/5,2015/5/6,2015/5/7,2015/5/8,2015/5/9,2015/6/1,2015/6/10,2015/6/11,2015/6/12,2015/6/13,2015/6/14,2015/6/15,2015/6/16,2015/6/17,2015/6/18,2015/6/19,2015/6/2,2015/6/20,2015/6/21,2015/6/22,2015/6/23,2015/6/24,2015/6/25,2015/6/26,2015/6/27,2015/6/28,2015/6/29,2015/6/3,2015/6/30,2015/6/4,2015/6/5,2015/6/6,2015/6/7,2015/6/8,2015/6/9,2015/7/1,2015/7/10,2015/7/11,2015/7/12,2015/7/13,2015/7/14,2015/7/15,2015/7/16,2015/7/17,2015/7/18,2015/7/19,2015/7/2,2015/7/20,2015/7/21,2015/7/22,2015/7/23,2015/7/24,2015/7/25,2015/7/26,2015/7/27,2015/7/28,2015/7/29,2015/7/3,2015/7/30,2015/7/31,2015/7/4,2015/7/5,2015/7/6,2015/7/7,2015/7/8,2015/7/9,2015/8/1,2015/8/10,2015/8/11,2015/8/12,2015/8/13,2015/8/14,2015/8/15,2015/8/16,2015/8/17,2015/8/18,2015/8/19,2015/8/2,2015/8/20,2015/8/21,2015/8/22,2015/8/23,2015/8/24,2015/8/25,2015/8/26,2015/8/27,2015/8/28,2015/8/29,2015/8/3,2015/8/30,2015/8/31,2015/8/4,2015/8/5,2015/8/6,2015/8/7,2015/8/8,2015/8/9,2015/9/1,2015/9/10,2015/9/11,2015/9/12,2015/9/13,2015/9/14,2015/9/15,2015/9/16,2015/9/17,2015/9/18,2015/9/19,2015/9/2,2015/9/20,2015/9/21,2015/9/22,2015/9/23,2015/9/24,2015/9/25,2015/9/26,2015/9/27,2015/9/28,2015/9/29,2015/9/3,2015/9/30,2015/9/4,2015/9/5,2015/9/6,2015/9/7,2015/9/8,2015/9/9,2016/1/1,2016/1/10,2016/1/11,2016/1/12,2016/1/13,2016/1/14,2016/1/15,2016/1/16,2016/1/17,2016/1/18,2016/1/19,2016/1/2,2016/1/20,2016/1/21,2016/1/22,2016/1/23,2016/1/24,2016/1/25,2016/1/26,2016/1/27,2016/1/28,2016/1/29,2016/1/3,2016/1/30,2016/1/31,2016/1/4,2016/1/5,2016/1/6,2016/1/7,2016/1/8,2016/1/9,2016/10/1,2016/10/10,2016/10/11,2016/10/12,2016/10/13,2016/10/14,2016/10/15,2016/10/16,2016/10/17,2016/10/18,2016/10/19,2016/10/2,2016/10/20,2016/10/21,2016/10/22,2016/10/23,2016/10/24,2016/10/25,2016/10/26,2016/10/27,2016/10/28,2016/10/29,2016/10/3,2016/10/30,2016/10/31,2016/10/4,2016/10/5,2016/10/6,2016/10/7,2016/10/8,2016/10/9,2016/2/1,2016/2/10,2016/2/11,2016/2/12,2016/2/13,2016/2/14,2016/2/15,2016/2/16,2016/2/17,2016/2/18,2016/2/19,2016/2/2,2016/2/20,2016/2/21,2016/2/22,2016/2/23,2016/2/24,2016/2/25,2016/2/26,2016/2/27,2016/2/28,2016/2/29,2016/2/3,2016/2/4,2016/2/5,2016/2/6,2016/2/7,2016/2/8,2016/2/9,2016/3/1,2016/3/10,2016/3/11,2016/3/12,2016/3/13,2016/3/14,2016/3/15,2016/3/16,2016/3/17,2016/3/18,2016/3/19,2016/3/2,2016/3/20,2016/3/21,2016/3/22,2016/3/23,2016/3/24,2016/3/25,2016/3/26,2016/3/27,2016/3/28,2016/3/29,2016/3/3,2016/3/30,2016/3/31,2016/3/4,2016/3/5,2016/3/6,2016/3/7,2016/3/8,2016/3/9,2016/4/1,2016/4/10,2016/4/11,2016/4/12,2016/4/13,2016/4/14,2016/4/15,2016/4/16,2016/4/17,2016/4/18,2016/4/19,2016/4/2,2016/4/20,2016/4/21,2016/4/22,2016/4/23,2016/4/24,2016/4/25,2016/4/26,2016/4/27,2016/4/28,2016/4/29,2016/4/3,2016/4/30,2016/4/4,2016/4/5,2016/4/6,2016/4/7,2016/4/8,2016/4/9,2016/5/1,2016/5/10,2016/5/11,2016/5/12,2016/5/13,2016/5/14,2016/5/15,2016/5/16,2016/5/17,2016/5/18,2016/5/19,2016/5/2,2016/5/20,2016/5/21,2016/5/22,2016/5/23,2016/5/24,2016/5/25,2016/5/26,2016/5/27,2016/5/28,2016/5/29,2016/5/3,2016/5/30,2016/5/31,2016/5/4,2016/5/5,2016/5/6,2016/5/7,2016/5/8,2016/5/9,2016/6/1,2016/6/10,2016/6/11,2016/6/12,2016/6/13,2016/6/14,2016/6/15,2016/6/16,2016/6/17,2016/6/18,2016/6/19,2016/6/2,2016/6/20,2016/6/21,2016/6/22,2016/6/23,2016/6/24,2016/6/25,2016/6/26,2016/6/27,2016/6/28,2016/6/29,2016/6/3,2016/6/30,2016/6/4,2016/6/5,2016/6/6,2016/6/7,2016/6/8,2016/6/9,2016/7/1,2016/7/10,2016/7/11,2016/7/12,2016/7/13,2016/7/14,2016/7/15,2016/7/16,2016/7/17,2016/7/18,2016/7/19,2016/7/2,2016/7/20,2016/7/21,2016/7/22,2016/7/23,2016/7/24,2016/7/25,2016/7/26,2016/7/27,2016/7/28,2016/7/29,2016/7/3,2016/7/30,2016/7/31,2016/7/4,2016/7/5,2016/7/6,2016/7/7,2016/7/8,2016/7/9,2016/8/1,2016/8/10,2016/8/11,2016/8/12,2016/8/13,2016/8/14,2016/8/15,2016/8/16,2016/8/17,2016/8/18,2016/8/19,2016/8/2,2016/8/20,2016/8/21,2016/8/22,2016/8/23,2016/8/24,2016/8/25,2016/8/26,2016/8/27,2016/8/28,2016/8/29,2016/8/3,2016/8/30,2016/8/31,2016/8/4,2016/8/5,2016/8/6,2016/8/7,2016/8/8,2016/8/9,2016/9/1,2016/9/10,2016/9/11,2016/9/12,2016/9/13,2016/9/14,2016/9/15,2016/9/16,2016/9/17,2016/9/19,2016/9/2,2016/9/20,2016/9/21,2016/9/22,2016/9/23,2016/9/24,2016/9/25,2016/9/26,2016/9/27,2016/9/28,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,FLAG,mean_consumption,std_consumption,cv,num_zeros,trend_slope,sudden_drop_count,min_consumption,max_consumption,median_consumption,num_below_mean,skewness,iqr,max_drop_pct
0,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,26.26000,22.87000,22.43000,25.28000,21.17000,20.44000,20.68000,21.14000,20.16000,19.97000,21.89000,25.08000,21.96000,22.52000,20.90000,20.28000,20.05000,20.93000,21.93000,21.01000,22.30000,19.25000,13.898342,24.40000,46.42000,22.91000,23.48000,22.98000,23.27000,22.68000,22.98000,38.26000,18.55000,22.48000,18.94000,22.31000,20.65000,18.61000,22.37000,19.96000,18.33000,17.59000,21.93000,18.14000,17.79000,11.88000,6.07000,6.24000,5.54000,6.45000,5.42000,6.01000,5.79000,20.36000,6.41000,20.52000,20.72000,19.61000,18.64000,20.39000,21.65000,5.58000,6.11000,6.69000,6.16000,6.48000,6.94000,5.80000,6.53000,13.898342,13.898342,13.898342,6.78000,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,5.49000,13.898342,13.898342,6.83000,6.94000,6.24000,7.44000,5.69000,6.57000,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,6.410000,6.680000,7.150000,6.000000,5.020000,6.890000,6.910000,8.260000,5.550000,5.370000,8.300000,4.720000,6.560000,4.940000,7.890000,5.080000,6.570000,5.200000,4.780000,4.460000,4.900000,7.570000,6.080000,6.590000,7.010000,7.610000,8.100000,4.540000,7.780000,8.570000,7.060000,8.030000,8.700000,7.850000,7.270000,6.260000,8.320000,7.110000,6.520000,6.180000,13.898342,10.420000,6.320000,6.140000,5.500000,5.070000,8.910000,6.970000,8.300000,8.010000,6.810000,5.580000,7.570000,6.640000,8.010000,7.160000,8.170000,8.600000,7.850000,8.490000,6.590000,7.370000,7.620000,6.710000,7.130000,7.720000,7.700000,7.560000,8.280000,7.880000,13.898342,7.920000,5.800000,5.880000,6.670000,6.590000,7.530000,6.590000,7.600000,6.360000,7.830000,6.370000,6.500000,7.290000,6.920000,7.050000,6.780000,7.290000,6.680000,7.000000,7.590000,9.760000,7.200000,6.370000,7.820000,7.470000,7.110000,7.630000,8.000000,9.360000,11.400000,8.560000,8.480000,7.820000,10.430000,14.200000,7.390000,6.760000,8.240000,14.580000,14.350000,19.030000,12.170000,7.450000,16.830000,7.180000,6.950000,6.340000,7.240000,6.480000,7.200000,22.260000,25.430000,29.320000,27.620000,35.550000,18.100000,21.940000,23.280000,24.810000,28.290000,24.960000,25.210000,22.380000,23.790000,23.760000,18.360000,15.670000,16.970000,23.610000,25.020000,21.220000,25.120000,22.640000,29.320000,28.080000,22.520000,26.090000,20.800000,22.920000,23.420000,27.910000,27.850000,24.080000,17.390000,14.730000,16.810000,18.680000,19.560000,17.940000,18.460000,16.450000,13.610000,29.950000,12.210000,11.370000,15.510000,18.210000,18.080000,16.310000,21.20000,19.14000,17.08000,17.82000,23.380000,18.31000,17.29000,26.800000,25.820000,29.220000,26.520000,30.250000,28.640000,15.50000,17.57000,18.52000,25.06000,22.49000,28.70000,18.36000,17.30000,18.62000,20.62000,26.62000,19.32000,13.28000,12.47000,26.20000,27.99000,33.68000,29.82000,30.19000,35.23000,32.44000,41.51000,16.38000,33.11000,14.08000,15.71000,15.70000,24.01000,26.28000,18.66000,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,13.898342,9.20,12.65,6.72,6.69,9.13,8.42,8.47,11.65,9.76,5.74,8.08,9.05,5.94,6.20,6.00,10.09,14.68,6.65,8.04,9.95,13.75,9.74,9.73,12.27,7.80,5.10,5.34,4.36,4.76,10.32,7.03,18.19000,6.50,8.08,7.97,8.81,7.37,11.72,11.02,8.18,7.33,6.71,10.93000,8.52,6.31,7.18,8.07,8.09,9.53,5.48,8.75,9.30,7.54,11.41000,9.16,6.74,19.92000,10.70000,9.20000,6.77000,6.76,6.15,9.51,8.96,13.35,12.17,11.16,9.75,12.81,11.52,14.64,11.59,12.21,13.14,7.50,11.74,12.82,9.89,9.06,9.75,12.84,8.65,12.16,5.81,10.49,15.96,22.64,22.31,15.27,9.24,12.62,9.70,8.19,11.97,11.99,9.94,8.00,9.18,10.49,6.80,8.46,6.61,8.69,10.50,7.17,6.40,7.32,9.98,9.67,10.62,12.95,8.72,6.28,6.85,7.00,5.86,10.44,9.38,9.53,7.72,7.85,8.06,8.55,12.20,6.51,7.61,5.94,8.67,11.04,8.11,12.28,5.69,7.36,8.34,7.51,7.52,12.08,7.05,8.52,5.92,7.21,7.79,8.39,8.80,11.00,11.39,9.37,6.62,7.68,6.16,9.34,7.23,12.25,6.99,4.85,5.84,9.48,8.78,7.95000,3.12000,4.67,4.85,3.86,9.43,5.39,5.37,9.00,6.66,4.99,6.81,4.36,10.51,14.29,15.80,5.23,10.59,4.65,7.13,5.20,6.48,9.48,8.52,5.07,14.08,19.58,14.53,7.78,6.08,6.41,5.52,7.99,12.06,8.96,21.08,7.65,15.06,16.91,14.70,25.08,32.24,35.95,21.27,15.72,26.52,31.08,8.53,22.28,12.84,9.49,5.55,9.86,9.01,15.41,30.13,27.19,23.59,22.43,27.54,35.04,31.30,36.13,30.47,20.69,18.96,35.86,33.71,32.10,35.31,31.66,44.06,36.41,37.59,36.44,23.81,12.98,39.58,2.90,4.36,24.81,25.56,21.62,37.62,34.680000,26.53,5.82,10.21,2.79,4.98,7.62,4.55,17.16,33.86,26.85,32.28,31.07,7.65,35.48,34.05,34.73,35.66,46.49,34.62000,35.67000,35.57000,20.89000,11.85000,2.46,7.58000,18.84000,9.77,9.07,8.96,5.24,10.61,10.84,19.13000,18.00000,15.95000,5.26000,8.35000,10.23000,10.080000,11.620000,12.320000,12.18000,20.89000,7.07000,6.31000,8.56000,10.48000,8.20000,12.53000,7.90000,8.58000,10.12000,9.96000,16.92000,7.60000,27.22000,18.05000,26.47000,18.75000,17.84000,14.92000,1.0,13.898342,6.683785,0.480905,0,-0.000364,46,2.46,46.49,13.898342,811,1.513367,5.095842,0.926731

In [65]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

2014/1/1              0
2014/1/10             0
2014/1/11             0
2014/1/12             0
2014/1/13             0
2014/1/14             0
2014/1/15             0
2014/1/16             0
2014/1/17             0
2014/1/18             0
2014/1/19             0
2014/1/2              0
2014/1/20             0
2014/1/21             0
2014/1/22             0
2014/1/23             0
2014/1/24             0
2014/1/25             0
2014/1/26             0
2014/1/27             0
2014/1/28             0
2014/1/29             0
2014/1/3              0
2014/1/30             0
2014/1/31             0
2014/1/4              0
2014/1/5              0
2014/1/6              0
2014/1/7              0
2014/1/8              0
2014/1/9              0
2014/10/1             0
2014/10/10            0
2014/10/11            0
2014/10/12            0
2014/10/13            0
2014/10/14            0
2014/10/15            0
2014/10/16            0
2014/10/17            0
2014/10/18            0
2014/10/19            0
2014/10/2             0
2014/10/20            0
2014/10/21            0
2014/10/22            0
2014/10/23            0
2014/10/24            0
2014/10/25            0
2014/10/26            0
2014/10/27            0
2014/10/28            0
2014/10/29            0
2014/10/3             0
2014/10/30            0
2014/10/31            0
2014/10/4             0
2014/10/5             0
2014/10/6             0
2014/10/7             0
2014/10/8             0
2014/10/9             0
2014/11/1             0
2014/11/10            0
2014/11/11            0
2014/11/12            0
2014/11/13            0
2014/11/14            0
2014/11/15            0
2014/11/16            0
2014/11/17            0
2014/11/18            0
2014/11/19            0
2014/11/2             0
2014/11/20            0
2014/11/21            0
2014/11/22            0
2014/11/23            0
2014/11/24            0
2014/11/25            0
2014/11/26            0
2014/11/27            0
2014/11/28            0
2014/11/29            0
2014/11/3             0
2014/11/30            0
2014/11/4             0
2014/11/5             0
2014/11/6             0
2014/11/7             0
2014/11/8             0
2014/11/9             0
2014/12/1             0
2014/12/10            0
2014/12/11            0
2014/12/12            0
2014/12/13            0
2014/12/14            0
2014/12/15            0
2014/12/16            0
2014/12/17            0
2014/12/18            0
2014/12/19            0
2014/12/2             0
2014/12/20            0
2014/12/21            0
2014/12/22            0
2014/12/23            0
2014/12/24            0
2014/12/25            0
2014/12/26            0
2014/12/27            0
2014/12/28            0
2014/12/29            0
2014/12/3             0
2014/12/30            0
2014/12/31            0
2014/12/4             0
2014/12/5             0
2014/12/6             0
2014/12/7             0
2014/12/8             0
2014/12/9             0
2014/2/1              0
2014/2/10             0
2014/2/11             0
2014/2/12             0
2014/2/13             0
2014/2/14             0
2014/2/15             0
2014/2/16             0
2014/2/17             0
2014/2/18             0
2014/2/19             0
2014/2/2              0
2014/2/20             0
2014/2/21             0
2014/2/22             0
2014/2/23             0
2014/2/24             0
2014/2/25             0
2014/2/26             0
2014/2/27             0
2014/2/28             0
2014/2/3              0
2014/2/4              0
2014/2/5              0
2014/2/6              0
2014/2/7              0
2014/2/8              0
2014/2/9              0
2014/3/1              0
2014/3/10             0
2014/3/11             0
2014/3/12             0
2014/3/13             0
2014/3/14             0
2014/3/15             0
2014/3/16             0
2014/3/17             0
2014/3/18             0
2014/3/19             0
2014/3/2              0
2014/3/20             0
2014/3/21             0
2014/3/22             0
2014/3/23             0
2014/3/24             0
2014/3/25             0
2014/3/26             0
2014/3/27             0
2014/3/28             0
2014/3/29             0
2014/3/3              0
2014/3/30             0
2014/3/31             0
2014/3/4              0
2014/3/5              0
2014/3/6              0
2014/3/7              0
2014/3/8              0
2014/3/9              0
2014/4/1              0
2014/4/10             0
2014/4/11             0
2014/4/12             0
2014/4/13             0
2014/4/14             0
2014/4/15             0
2014/4/16             0
2014/4/17             0
2014/4/18             0
2014/4/19             0
2014/4/2              0
2014/4/20             0
2014/4/21             0
2014/4/22             0
2014/4/23             0
2014/4/24             0
2014/4/25             0
2014/4/26             0
2014/4/27             0
2014/4/28             0
2014/4/29             0
2014/4/3              0
2014/4/30             0
2014/4/4              0
2014/4/5              0
2014/4/6              0
2014/4/7              0
2014/4/8              0
2014/4/9              0
2014/5/1              0
2014/5/10             0
2014/5/11             0
2014/5/12             0
2014/5/13             0
2014/5/14             0
2014/5/15             0
2014/5/16             0
2014/5/17             0
2014/5/18             0
2014/5/19             0
2014/5/2              0
2014/5/20             0
2014/5/21             0
2014/5/22             0
2014/5/23             0
2014/5/24             0
2014/5/25             0
2014/5/26             0
2014/5/27             0
2014/5/28             0
2014/5/29             0
2014/5/3              0
2014/5/30             0
2014/5/31             0
2014/5/4              0
2014/5/5              0
2014/5/6              0
2014/5/7              0
2014/5/8              0
2014/5/9              0
2014/6/1              0
2014/6/10             0
2014/6/11             0
2014/6/12             0
2014/6/13             0
2014/6/14             0
2014/6/15             0
2014/6/16             0
2014/6/17             0
2014/6/18             0
2014/6/19             0
2014/6/2              0
2014/6/20             0
2014/6/21             0
2014/6/22             0
2014/6/23             0
2014/6/24             0
2014/6/25             0
2014/6/26             0
2014/6/27             0
2014/6/28             0
2014/6/29             0
2014/6/3              0
2014/6/30             0
2014/6/4              0
2014/6/5              0
2014/6/6              0
2014/6/7              0
2014/6/8              0
2014/6/9              0
2014/7/1              0
2014/7/10             0
2014/7/11             0
2014/7/12             0
2014/7/13             0
2014/7/14             0
2014/7/15             0
2014/7/16             0
2014/7/17             0
2014/7/18             0
2014/7/19             0
2014/7/2              0
2014/7/20             0
2014/7/21             0
2014/7/22             0
2014/7/23             0
2014/7/24             0
2014/7/25             0
2014/7/26             0
2014/7/27             0
2014/7/28             0
2014/7/29             0
2014/7/3              0
2014/7/30             0
2014/7/31             0
2014/7/4              0
2014/7/5              0
2014/7/6              0
2014/7/7              0
2014/7/8              0
2014/7/9              0
2014/8/1              0
2014/8/10             0
2014/8/11             0
2014/8/12             0
2014/8/13             0
2014/8/14             0
2014/8/15             0
2014/8/16             0
2014/8/17             0
2014/8/18             0
2014/8/19             0
2014/8/2              0
2014/8/20             0
2014/8/21             0
2014/8/22             0
2014/8/23             0
2014/8/24             0
2014/8/25             0
2014/8/26             0
2014/8/27             0
2014/8/28             0
2014/8/29             0
2014/8/3              0
2014/8/30             0
2014/8/31             0
2014/8/4              0
2014/8/5              0
2014/8/6              0
2014/8/7              0
2014/8/8              0
2014/8/9              0
2014/9/1              0
2014/9/10             0
2014/9/11             0
2014/9/12             0
2014/9/13             0
2014/9/14             0
2014/9/15             0
2014/9/16             0
2014/9/17             0
2014/9/18             0
2014/9/19             0
2014/9/2              0
2014/9/20             0
2014/9/21             0
2014/9/22             0
2014/9/23             0
2014/9/24             0
2014/9/25             0
2014/9/26             0
2014/9/27             0
2014/9/28             0
2014/9/29             0
2014/9/3              0
2014/9/30             0
2014/9/4              0
2014/9/5              0
2014/9/6              0
2014/9/7              0
2014/9/8              0
2014/9/9              0
2015/1/1              0
2015/1/10             0
2015/1/11             0
2015/1/12             0
2015/1/13             0
2015/1/14             0
2015/1/15             0
2015/1/16             0
2015/1/17             0
2015/1/18             0
2015/1/19             0
2015/1/2              0
2015/1/20             0
2015/1/21             0
2015/1/22             0
2015/1/23             0
2015/1/24             0
2015/1/25             0
2015/1/26             0
2015/1/27             0
2015/1/28             0
2015/1/29             0
2015/1/3              0
2015/1/30             0
2015/1/31             0
2015/1/4              0
2015/1/5              0
2015/1/6              0
2015/1/7              0
2015/1/8              0
2015/1/9              0
2015/10/1             0
2015/10/10            0
2015/10/11            0
2015/10/12            0
2015/10/13            0
2015/10/14            0
2015/10/15            0
2015/10/16            0
2015/10/17            0
2015/10/18            0
2015/10/19            0
2015/10/2             0
2015/10/20            0
2015/10/21            0
2015/10/22            0
2015/10/23            0
2015/10/24            0
2015/10/25            0
2015/10/26            0
2015/10/27            0
2015/10/28            0
2015/10/29            0
2015/10/3             0
2015/10/30            0
2015/10/31            0
2015/10/4             0
2015/10/5             0
2015/10/6             0
2015/10/7             0
2015/10/8             0
2015/10/9             0
2015/11/1             0
2015/11/10            0
2015/11/11            0
2015/11/12            0
2015/11/13            0
2015/11/14            0
2015/11/15            0
2015/11/16            0
2015/11/17            0
2015/11/18            0
2015/11/19            0
2015/11/2             0
2015/11/20            0
2015/11/21            0
2015/11/22            0
2015/11/23            0
2015/11/24            0
2015/11/25            0
2015/11/26            0
2015/11/27            0
2015/11/28            0
2015/11/29            0
2015/11/3             0
2015/11/30            0
2015/11/4             0
2015/11/5             0
2015/11/6             0
2015/11/7             0
2015/11/8             0
2015/11/9             0
2015/12/1             0
2015/12/10            0
2015/12/11            0
2015/12/12            0
2015/12/13            0
2015/12/14            0
2015/12/15            0
2015/12/16            0
2015/12/17            0
2015/12/18            0
2015/12/19            0
2015/12/2             0
2015/12/20            0
2015/12/21            0
2015/12/22            0
2015/12/23            0
2015/12/24            0
2015/12/25            0
2015/12/26            0
2015/12/27            0
2015/12/28            0
2015/12/29            0
2015/12/3             0
2015/12/30            0
2015/12/31            0
2015/12/4             0
2015/12/5             0
2015/12/6             0
2015/12/7             0
2015/12/8             0
2015/12/9             0
2015/2/1              0
2015/2/10             0
2015/2/11             0
2015/2/12             0
2015/2/13             0
2015/2/14             0
2015/2/15             0
2015/2/16             0
2015/2/17             0
2015/2/18             0
2015/2/19             0
2015/2/2              0
2015/2/20             0
2015/2/21             0
2015/2/22             0
2015/2/23             0
2015/2/24             0
2015/2/25             0
2015/2/26             0
2015/2/27             0
2015/2/28             0
2015/2/3              0
2015/2/4              0
2015/2/5              0
2015/2/6              0
2015/2/7              0
2015/2/8              0
2015/2/9              0
2015/3/1              0
2015/3/10             0
2015/3/11             0
2015/3/12             0
2015/3/13             0
2015/3/14             0
2015/3/15             0
2015/3/16             0
2015/3/17             0
2015/3/18             0
2015/3/19             0
2015/3/2              0
2015/3/20             0
2015/3/21             0
2015/3/22             0
2015/3/23             0
2015/3/24             0
2015/3/25             0
2015/3/26             0
2015/3/27             0
2015/3/28             0
2015/3/29             0
2015/3/3              0
2015/3/30             0
2015/3/31             0
2015/3/4              0
2015/3/5              0
2015/3/6              0
2015/3/7              0
2015/3/8              0
2015/3/9              0
2015/4/1              0
2015/4/10             0
2015/4/11             0
2015/4/12             0
2015/4/13             0
2015/4/14             0
2015/4/15             0
2015/4/16             0
2015/4/17             0
2015/4/18             0
2015/4/19             0
2015/4/2              0
2015/4/20             0
2015/4/21             0
2015/4/22             0
2015/4/23             0
2015/4/24             0
2015/4/25             0
2015/4/26             0
2015/4/27             0
2015/4/28             0
2015/4/29             0
2015/4/3              0
2015/4/30             0
2015/4/4              0
2015/4/5              0
2015/4/6              0
2015/4/7              0
2015/4/8              0
2015/4/9              0
2015/5/1              0
2015/5/10             0
2015/5/11             0
2015/5/12             0
2015/5/13             0
2015/5/14             0
2015/5/15             0
2015/5/16             0
2015/5/17             0
2015/5/18             0
2015/5/19             0
2015/5/2              0
2015/5/20             0
2015/5/21             0
2015/5/22             0
2015/5/23             0
2015/5/24             0
2015/5/25             0
2015/5/26             0
2015/5/27             0
2015/5/28             0
2015/5/29             0
2015/5/3              0
2015/5/30             0
2015/5/31             0
2015/5/4              0
2015/5/5              0
2015/5/6              0
2015/5/7              0
2015/5/8              0
2015/5/9              0
2015/6/1              0
2015/6/10             0
2015/6/11             0
2015/6/12             0
2015/6/13             0
2015/6/14             0
2015/6/15             0
2015/6/16             0
2015/6/17             0
2015/6/18             0
2015/6/19             0
2015/6/2              0
2015/6/20             0
2015/6/21             0
2015/6/22             0
2015/6/23             0
2015/6/24             0
2015/6/25             0
2015/6/26             0
2015/6/27             0
2015/6/28             0
2015/6/29             0
2015/6/3              0
2015/6/30             0
2015/6/4              0
2015/6/5              0
2015/6/6              0
2015/6/7              0
2015/6/8              0
2015/6/9              0
2015/7/1              0
2015/7/10             0
2015/7/11             0
2015/7/12             0
2015/7/13             0
2015/7/14             0
2015/7/15             0
2015/7/16             0
2015/7/17             0
2015/7/18             0
2015/7/19             0
2015/7/2              0
2015/7/20             0
2015/7/21             0
2015/7/22             0
2015/7/23             0
2015/7/24             0
2015/7/25             0
2015/7/26             0
2015/7/27             0
2015/7/28             0
2015/7/29             0
2015/7/3              0
2015/7/30             0
2015/7/31             0
2015/7/4              0
2015/7/5              0
2015/7/6              0
2015/7/7              0
2015/7/8              0
2015/7/9              0
2015/8/1              0
2015/8/10             0
2015/8/11             0
2015/8/12             0
2015/8/13             0
2015/8/14             0
2015/8/15             0
2015/8/16             0
2015/8/17             0
2015/8/18             0
2015/8/19             0
2015/8/2              0
2015/8/20             0
2015/8/21             0
2015/8/22             0
2015/8/23             0
2015/8/24             0
2015/8/25             0
2015/8/26             0
2015/8/27             0
2015/8/28             0
2015/8/29             0
2015/8/3              0
2015/8/30             0
2015/8/31             0
2015/8/4              0
2015/8/5              0
2015/8/6              0
2015/8/7              0
2015/8/8              0
2015/8/9              0
2015/9/1              0
2015/9/10             0
2015/9/11             0
2015/9/12             0
2015/9/13             0
2015/9/14             0
2015/9/15             0
2015/9/16             0
2015/9/17             0
2015/9/18             0
2015/9/19             0
2015/9/2              0
2015/9/20             0
2015/9/21             0
2015/9/22             0
2015/9/23             0
2015/9/24             0
2015/9/25             0
2015/9/26             0
2015/9/27             0
2015/9/28             0
2015/9/29             0
2015/9/3              0
2015/9/30             0
2015/9/4              0
2015/9/5              0
2015/9/6              0
2015/9/7              0
2015/9/8              0
2015/9/9              0
2016/1/1              0
2016/1/10             0
2016/1/11             0
2016/1/12             0
2016/1/13             0
2016/1/14             0
2016/1/15             0
2016/1/16             0
2016/1/17             0
2016/1/18             0
2016/1/19             0
2016/1/2              0
2016/1/20             0
2016/1/21             0
2016/1/22             0
2016/1/23             0
2016/1/24             0
2016/1/25             0
2016/1/26             0
2016/1/27             0
2016/1/28             0
2016/1/29             0
2016/1/3              0
2016/1/30             0
2016/1/31             0
2016/1/4              0
2016/1/5              0
2016/1/6              0
2016/1/7              0
2016/1/8              0
2016/1/9              0
2016/10/1             0
2016/10/10            0
2016/10/11            0
2016/10/12            0
2016/10/13            0
2016/10/14            0
2016/10/15            0
2016/10/16            0
2016/10/17            0
2016/10/18            0
2016/10/19            0
2016/10/2             0
2016/10/20            0
2016/10/21            0
2016/10/22            0
2016/10/23            0
2016/10/24            0
2016/10/25            0
2016/10/26            0
2016/10/27            0
2016/10/28            0
2016/10/29            0
2016/10/3             0
2016/10/30            0
2016/10/31            0
2016/10/4             0
2016/10/5             0
2016/10/6             0
2016/10/7             0
2016/10/8             0
2016/10/9             0
2016/2/1              0
2016/2/10             0
2016/2/11             0
2016/2/12             0
2016/2/13             0
2016/2/14             0
2016/2/15             0
2016/2/16             0
2016/2/17             0
2016/2/18             0
2016/2/19             0
2016/2/2              0
2016/2/20             0
2016/2/21             0
2016/2/22             0
2016/2/23             0
2016/2/24             0
2016/2/25             0
2016/2/26             0
2016/2/27             0
2016/2/28             0
2016/2/29             0
2016/2/3              0
2016/2/4              0
2016/2/5              0
2016/2/6              0
2016/2/7              0
2016/2/8              0
2016/2/9              0
2016/3/1              0
2016/3/10             0
2016/3/11             0
2016/3/12             0
2016/3/13             0
2016/3/14             0
2016/3/15             0
2016/3/16             0
2016/3/17             0
2016/3/18             0
2016/3/19             0
2016/3/2              0

In [66]:
new_df = df[['FLAG','mean_consumption', 'std_consumption', 'cv', 'num_zeros', 'trend_slope', 'sudden_drop_count', 'min_consumption', 'max_consumption', 'median_consumption', 'num_below_mean', 'skewness', 'iqr', 'max_drop_pct']]

In [67]:
new_df.head()

,FLAG,mean_consumption,std_consumption,cv,num_zeros,trend_slope,sudden_drop_count,min_consumption,max_consumption,median_consumption,num_below_mean,skewness,iqr,max_drop_pct
0,1.0,13.898342,6.683785,0.480905,0,-0.000364,46,2.46,46.49,13.898342,811,1.513367,5.095842,0.926731
1,1.0,0.000000,0.000000,0.000000,1034,0.000000,0,0.00,0.00,0.000000,0,0.000000,0.000000,0.000000
2,1.0,9.921390,3.409611,0.343663,41,-0.000358,15,0.00,32.81,9.921390,160,1.976875,0.000000,1.000000
3,1.0,14.612055,7.712976,0.527850,0,0.012225,56,0.40,52.76,14.612055,266,0.984226,0.399555,0.992418
4,1.0,8.249738,5.930837,0.718912,0,0.010040,51,0.85,43.43,6.280000,694,2.597712,5.197500,0.750733

In [68]:
new_df.shape

(77510, 14)

In [69]:
new_df.to_csv('dataset.csv', index=False)